### ISSUE TITLE
Support KnowledgeRepositories based on remote git urls

### ISSUE THREAD

**Issue by ajbosco** [airbnb/knowledge-repo#124]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Does the git repo need to be cloned to the production web server or does the <repo_path> in the deploy point to a hosted repo?

**Comment by earthmancash** [comment]
Hey there @ajbosco ! The git repo needs to be cloned to the production web server currently. It might be an interesting case to build another repository class for reading from a hosted backend, but we don't have that right now.
