### ISSUE TITLE
Automatically refreshing origin

### ISSUE THREAD

**Issue by karlmoller** [airbnb/knowledge-repo#127]
How do I setup a knowledge-repo server to always get the latest repository snapshot when a user accesses the knowledge-repo web server? At the moment I have to restart the server after every new submission. 

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Hi @karlmoller,

Thanks for reaching out :). As of early this morning, the knowledge repository will automatically update the post index when the git repository is updated. At the moment, the git repository must be updated separately (manually or via cron or some other scheduling service). In the future the git repository itself will have the option of being directly pulled.

I'm going to close this issue but tag it in #67; which is the issue addressing full support of the KnowledgeRepository API.

Let me know if you have any other questions!

M
