### ISSUE TITLE
Add separate documentation for Windows installations?

### ISSUE THREAD

**Issue by RMHogervorst** [airbnb/knowledge-repo#133]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
This is probably a good idea. Do you have some expertise setting up Windows environments for this sort of thing? We fixed the code to work on Windows, but are not sure how the community at large deals with Windows installations.

**Comment by RMHogervorst** [comment]
Unfortunately my only experience is with my own computer.

Op 10 nov. 2016 07:54 schreef "Matthew Wardrop" <notifications@github.com>:

**Comment by gstoel** [comment]
Here also someone who is willing to help/test stuff out to get this working on windows. 
currently it fails to run on windows with ImportError: No module named fcntl (which I think is due to the fact that gunicorn is not supported under windows). 

@matthewwardrop you mention you have fixed the code to work on Windows right? Unfortunately not at ' my Windows'  :) so willing to help get it working there and feed back to the community.

**Comment by RMHogervorst** [comment]
I'm willing to test but I'm a Python novice. So I'll not take the lead here

Op 15 nov. 2016 6:02 p.m. schreef "Geoffrey Stoel" <notifications@github.com

**Comment by gnatamania** [comment]
If it's possible to get this to work on windows I would love to see some documentation on this! I've been trying to step through the code and fix myself to no avail :(

**Comment by bdoohan** [comment]
@matthewwardrop I have come across the same issue, seeing "ImportError: No module named 'fcntl'" when I try to preview my post. Has anyone developed a fix for this?

**Comment by bdoohan** [comment]
@matthewwardrop @earthmancash To follow up, I have come across the same issue, seeing "ImportError: No module named 'fcntl'" when I try to preview my post. Has anyone developed a fix for this?

**Comment by matthewwardrop** [comment]
@bdoohan This is fixed in #225. Whenever the deployment code was run, it would trigger this fault due to Gunicorn only supporting POSIX platforms. There was a related bug for the "create" action, which did not terminate the knowledge_repo script after a successful template creation, triggering the above bug also.

**Comment by matthewwardrop** [comment]
@gstoel @RMHogervorst @gnatamania Apart from the bug fixed above, are there any other issues that you experience?

**Comment by gstoel** [comment]
@matthewwardrop I will retry the installation later this week... will get back to you with details or other issues.

**Comment by RMHogervorst** [comment]
I will try the installation today and report back @matthewwardrop

**Comment by gnatamania** [comment]
@matthewwardrop I will try out a clean install next week and get back to you. Really looking forward to getting this to work :)

**Comment by matthewwardrop** [comment]
@gstoel @RMHogervorst @gnatamania As of today, we now do continuous integration testing against Windows too; so we should be protected against inadvertently breaking the Windows build in the future. Additionally, I've fixed everything that I found breaking the Windows build, and we now pass the continuous integration suite.

**Comment by RMHogervorst** [comment]
It works on windows! (version 0.7.6)
Running the example (starting with a clean folder, and adding a rmarkdown file ) .

There is one problem: images are created, but not linked to in the preview. 

I did notice that images are placed in `figure` in my folder, and the website searches in `images`:

`<p><img alt="plot of chunk unnamed-chunk-1" src="images\unnamed-chunk-1-1.png" /></p>`

**Comment by matthewwardrop** [comment]
@RMHogervorst Ah! Looks like the paths are using Windows style paths instead of the standard path format (i.e. using '\' rather than '/' as the path separator). I bet that's the issue.

In the generated knowledge post folder, is there an 'images' folder with all the images?

**Comment by RMHogervorst** [comment]
in the final repo there is indeed an images folder and a orig_src folder. The md file has 
this link 
`![plot of chunk unnamed-chunk-2](images\unnamed-chunk-2-1.png)`

**Comment by matthewwardrop** [comment]
Yep... that's the problem then. I'll submit a patch for this soon :).
