### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by mentat2737** [airbnb/knowledge-repo#137]
Would be nice to have a docker image available, or at least instructions on how to make one.

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Hi @mentat2737, Docker images are coming! For now, I'll merge this into #136. Thanks for your continued interest!

**Comment by mentat2737** [comment]
Perfect, thanks for the reply.
