### ISSUE TITLE
Preview function doesn't work

### ISSUE THREAD

**Issue by pekovits** [airbnb/knowledge-repo#143]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Once the web app is deployed and trying to open the post, it can't open it. I get an error message saying "Looks like something is broken"

**Comment by matthewwardrop** [comment]
Hi @pekovits,

Can you try running the preview in debug mode? Try : `knowledge_repo
--debug preview ...`. This should provide the traceback log, so we can
actually see what's going on :).

**Comment by pekovits** [comment]
Hi @matthewwardrop,

Please find attached a txt file with the output from running preview in debug mode.
[log.txt](https://github.com/airbnb/knowledge-repo/files/594136/log.txt)

**Comment by pekovits** [comment]
Hi @matthewwardrop,

I am glad to say that I have fixed my issue. I traced back at the error and found that the six module was not up to date. I updated with pip and now it works great.

Thanks

**Comment by matthewwardrop** [comment]
Hurrah! Thanks for letting us know @pekovits !
