### ISSUE TITLE
Batch tags route doesn't work

### ISSUE THREAD

**Issue by NiharikaRay** [airbnb/knowledge-repo#145]
During the demo yesterday, I noticed that this route doesn't work. The error message thrown was:

```AttributeError: 'Post' object has no attribute 'contains_excluded_tags```

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by earthmancash** [comment]
Fixed in https://github.com/airbnb/knowledge-repo/pull/158
