### ISSUE TITLE
Web-editing UI not visible

### ISSUE THREAD

**Issue by cosenal** [airbnb/knowledge-repo#151]
I am using v0.7.2 from pip and running the webserver from the following command:

```
knowledge_repo --repo {git}krepo --repo {webposts}sqlite:////tmp/knowledge.db:mypostreftable runserver --config server_config.py
```

In `server_config.py` there is a string:
```WEB_EDITOR_PREFIXES = ['webposts']```

According to the Readme, with that configuration I should be able to see web-editing UI options (such as »Create Post«), but I don't :(

<img width="1045" alt="screen shot 2016-11-24 at 14 31 31" src="https://cloud.githubusercontent.com/assets/1048336/20600896/2ac06546-b256-11e6-9469-95b171e9505d.png">

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by danfrankj** [comment]
Hey @cosenal, Thanks for your interest in the knowledge repo and for reporting this bug. 

I believe this PR https://github.com/airbnb/knowledge-repo/pull/140 addresses the issue. Please let us know if you still have issues!

Thanks!

**Comment by earthmancash** [comment]
@cosenal are you still having this issue?

**Comment by cosenal** [comment]
I've just tried `master` and it works now :+1: Closing the issue, thanks!
