### ISSUE TITLE
Centrally Control Users/Tags

### ISSUE THREAD

**Issue by koaning** [airbnb/knowledge-repo#157]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I'm following the tutorial in the documentation with the examples. Once I ran the commands from the documentation for `.ipynb` and `.Rmd` and then render I see a subtle but annoying  problem. 

![image](https://cloud.githubusercontent.com/assets/1019791/20796628/459efa68-b7d7-11e6-85ce-a4fcaef4fee8.png)

Because the authors of both posts decided to have a different standard of describing authors we now end up with a situation where the knowledge repository thinks there are 4 authors instead of two. (`Sally Smarts` vs. `sally_smarts`). The same thing happens with tags. 

Is there a way to centrally manage authors/tags?  One can imagine that a misspelling of a tag in the submitted notebook/rmd can render it nearly impossible to find.

**Comment by earthmancash** [comment]
Hey @koaning! Thanks for filing the issue. The way we check author matching a username format is via this username_parse() [function](https://github.com/airbnb/knowledge-repo/blob/master/knowledge_repo/config_defaults.py#L31-L35). That file will show up in the knowledge gitrepository on initialization as a file named .knowledge_repo_config.py. Within that function, we have an assert() that makes sure our internal format is followed.

Hope that helps!

**Comment by earthmancash** [comment]
If this fixes your issue, I'll make sure to clear this up more in the documentation

**Comment by earthmancash** [comment]
For tags, we have an endpoint /batch_tags, which is used to clean up these types of formatting differences. We've talked about having tags added purely through the web app with typeahead to encourage matching existing tags and format, but haven't aligned on that yet.

**Comment by earthmancash** [comment]
@koaning does the above solve your issue?

**Comment by koaning** [comment]
sorry for the late response. yes: this does solve the problem.

**Comment by earthmancash** [comment]
@koaning what do you think about the documentation we just added? https://github.com/airbnb/knowledge-repo/pull/175 Let us know if we can improve it more.

**Comment by matthewwardrop** [comment]
@koaning Closing for now. I think the main issues reported here have been dealt with. Feel free to reopen this issue if things remain unclear, or more needs to be done :).
