### ISSUE TITLE
How to quit the web app?

### ISSUE THREAD

**Issue by philipobrien** [airbnb/knowledge-repo#161]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Following the quick start guide, I run `knowledge_repo --repo ./example_repo preview project/example_ipynb` and can preview the example post successfully, but I can't then quit the web app? The usual suspects of `Ctrl-C` or `Ctrl-D` do nothing.

**Comment by Paul-Darius** [comment]
Do you mean you can not quit the preview in your terminal ?
-> Type "q", then y for "yes".

**Comment by philipobrien** [comment]
![image](https://cloud.githubusercontent.com/assets/1763813/21007213/ddf22a36-bd33-11e6-96de-ed2021d90910.png)

Nothing happens whatever command I enter

**Comment by earthmancash** [comment]
That's strange.. We usually kill it with Ctrl-C. I'll close this issue for now, but let us know if it comes up again.

**Comment by Paul-Darius** [comment]
Ok, I understand his question now and I actually have the same problem.
Let's suppose I deploy the server in background mode, and then I close the shell.
How do I stop the server? Should I kill -9 the process or is there a way to properly stop it?
Ctrl-C is a solution only if the server is running in the current shell.

**Comment by vatsaluc** [comment]
I have gone through the same issue and I resolved it by killing the process on port 7000.
Please use 
-> **fuser -k 7000/tcp** to kill the web deployment of knowledge repo
