### ISSUE TITLE
[Bug] Submit review for proxy post throws a path error

### ISSUE THREAD

**Issue by NiharikaRay** [airbnb/knowledge-repo#169]
`ValueError: Provided path '.' is outside of the knowledge repository.`
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by danfrankj** [comment]
This now returns a more informative error 
![image](https://cloud.githubusercontent.com/assets/616139/23672662/32b43092-0324-11e7-936b-334c27269f7e.png)

**Comment by danfrankj** [comment]
@NiharikaRay I think this is solved - please reopen if not
