### ISSUE TITLE
Remove jinja code from JS in markdown-base.html

### ISSUE THREAD

**Issue by NiharikaRay** [airbnb/knowledge-repo#193]
In `markdown-base.html`, there's some jinja code in JS, which is non-optimal. The reason we do this is because we needed to know if something was a webpost or not, but we can do that without inserting the jinja in the JS (perhaps through using `data-is-webpost` attribute in the html, which can be `1` if it's a webpost, 0 otherwise). 

Action items:
[] Remove jinja from JS
[] Use url_for for the button clicks, as opposed to manually setting the path. 

Auto-reviewers: @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
This is fixed by the recent pagination commits. Yay!
