### ISSUE TITLE
No such column error when running web app

### ISSUE THREAD

**Issue by retroam** [airbnb/knowledge-repo#202]
Have been getting this error when running the web app:

sqlalchemy.exc.NoSuchColumnError
NoSuchColumnError: "Could not locate column in row for column '0'"

Can't figure out where the bug resides and been following the documentation closely

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by earthmancash** [comment]
Hey @retroam! Sorry to hear that you're running into trouble. Can you paste the command you're using to run the application? And can you try running it with the --debug flag after the --repo's and paste the full output? Hopefully that'll give us some more info to help you out.

**Comment by retroam** [comment]
Sorry for the delayed response @earthmancash ... running the following command:

`knowledge_repo --debug --repo {git}ds_knowledge/ runserver`

get the following error:

>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1994, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
>     response = self.handle_exception(e)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
>     rv = self.preprocess_request()
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
>     rv = func()
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/knowledge_repo/app/app.py", line 126, in update_index_if_required
>     update_index()
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/knowledge_repo/app/index.py", line 86, in update_index
>     _update_index(current_app)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/knowledge_repo/app/index.py", line 148, in _update_index
>     IndexMetadata.set('lock', 'index', False)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/knowledge_repo/app/models.py", line 51, in set
>     m = db_session.query(IndexMetadata).filter(IndexMetadata.type == type).filter(IndexMetadata.name == name).first()
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2690, in first
>     ret = list(self[0:1])
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2482, in __getitem__
>     return list(res)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 90, in instances
>     util.raise_from_cause(err)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
>     rows = [proc(row) for row in fetch]
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 437, in _instance
>     loaded_instance, populate_existing, populations
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 498, in _populate_full
>     dict_[key] = getter(row)
>   File "/home/ec2-user/anaconda2/lib/python2.7/site-packages/sqlalchemy/engine/result.py", line 563, in _key_fallback
>     expression._string_or_unprintable(key))
> NoSuchColumnError: "Could not locate column in row for column '4'")


Thanks for your help!

**Comment by matthewwardrop** [comment]
Hi @retroam. I cannot reproduce this locally. Can you try installing git master and trying again?

`pip install --upgrade "git+https://github.com/airbnb/knowledge-repo.git#egg=knowledge_repo"`

If you still get the error, let me know! I'd like to fix this before rolling out the next version.

**Comment by retroam** [comment]
@matthewwardrop issue still there. might be something wrong with my local settings.

**Comment by matthewwardrop** [comment]
@retroam Was this sorted?
