### ISSUE TITLE
/tag_pages has not pagination

### ISSUE THREAD

**Issue by victor-vazquez** [airbnb/knowledge-repo#223]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hello, 

I'm not sure if this is in an existing issue, but I'm pretty sure /tag_pages doesn't have pagination. I would like to filter by a specific tag and read all of the posts related to it.

**Comment by matthewwardrop** [comment]
Thanks @victor-vazquez . Likely this is a result of the recent pagination rewrite, I'll make sure this gets fixed :).
