### ISSUE TITLE
support for javascript within a post

### ISSUE THREAD

**Issue by bmabey** [airbnb/knowledge-repo#238]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Nearly all of our IPython notebooks use [Bokeh](http://bokeh.pydata.org/en/latest/) which will load some custom javascript. When the notebook is rendered to markdown the JS loading gets lost in translation and the inserted HTML by bokeh is rendered as a code block:

![image](https://cloud.githubusercontent.com/assets/1837/23802505/d49baa5e-0570-11e7-9d28-f53d3579026d.png)

Is this a known issue/limitation? If so is there a current workaround or a fix in progress?

**Comment by matthewwardrop** [comment]
Thanks for reporting this! We weren't fully aware of this. We'll look into this soon :).

**Comment by matthewwardrop** [comment]
Should be fixed in #256. Tested with Plotly, and everything looks good. If this still doesn't work for you @bmabey, please reopen the issue :).

**Comment by bmabey** [comment]
Thanks @matthewwardrop! 

Are there any docs on how to get up and running on `master` so I can try this out? I've tried using pip install  git+https://github.com/airbnb/knowledge-repo.git` and `python setup.py install` but both result in `knowlege_repo` script in an un-runnable state. I get following message when I try to run it:

```
Traceback (most recent call last):
  File "/Users/bmabey/anaconda/bin/knowledge_repo", line 4, in <module>
    __import__('pkg_resources').run_script('knowledge-repo==0.7.6', 'knowledge_repo')
  File "/Users/bmabey/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/bmabey/anaconda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1491, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'knowledge_repo'
```

Any thoughts?

**Comment by matthewwardrop** [comment]
Hi @bmabey,

This is an odd error, but if worst comes to worst you can do: `./scripts/knowledge_repo` within the checkout out knowledge-repo git repository. I wonder if this has something to do with anaconda? You could also try installing it into a virtual environment too :).
