### ISSUE TITLE
[quickstart] create example post creates it in bad dir

### ISSUE THREAD

**Issue by pavopax** [airbnb/knowledge-repo#245]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

(Also see #244)

I'm following the quickstart in master repo. The create post command seems to create the file in wrong location. Instead of:

`knowledge_repo --repo ./scientific-knowledge create Rmd example_post.Rmd`

... I need to type:

`knowledge_repo --repo ./scientific-knowledge/ create Rmd ./scientific-knowledge/example_post.Rmd`

Alternatively, it seems that I can `cd scientific-knowledge` and create post there with:

`knowledge_repo --repo . create Rmd example_post2.Rmd`

Attached screenshot has details.

<img width="758" alt="screen shot 2017-03-20 at 11 36 01 am" src="https://cloud.githubusercontent.com/assets/6165713/24115814/ce55e346-0d61-11e7-8419-d5435106e546.png">

**Comment by matthewwardrop** [comment]
Hi @pavopax 

Thanks for getting in touch about issues you're having with the knowledge repository!

In this case, the behaviour your are experiencing is the intended behaviour (though I admit it's probably a little confusing and we're working on it).

The `create` command creates a template ipynb/Rmd/md file which you can edit locally. The only difference between these files and any other file is that it has some example headers (and some dummy content). It is not supposed to be directly added to the repository in this form. The `add` command is what you use to actually add a knowledge post to the repository (at which point it will exist inside of the repository file structure). The templates created using `create` should explicitly *not* be inside the git repository.

The correct flow is to:
- Create a template or add the YAML headers to an existing ipynb/Rmd/md file. e.g `knowledge_repo --repo <repo_dir> create <file to be created relative to current directory>
- Add this file to the repository as a draft, eg. `knowledge_repo --repo <repo_dir> add <path to post ipynb/Rmd/md file> -p <path inside of repository>`
- The submit your draft for review e.g. `knowledge_repo --repo <repo_dir> submit <path inside repository>`

When using git repositories, accepting the drafts means merging the resulting branch in to master. When using posts stored in a database, the publishing is handled through the web interface.

Does that help?

**Comment by pavopax** [comment]
Yes, got it to work. I think it would help if it was streamlined, so effort there will be appreciated!

Looking forward to seeing the progress!

**Comment by matthewwardrop** [comment]
Excellent! Thanks @pavopax! There are some improvements incoming, but I look forward to your future comments as they eventuate :).
