### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by Joaquimdcp** [airbnb/knowledge-repo#249]
Hi!

Can I use a users system with knowledge-repo(login system)?

Thanks a lot!

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Hi @Joaquimdcp!

We're yet to have a working authentication system apart from having the headers added by some proxying agent... but work will soon begin on it. For now let's track this in #231.

Thanks so much for your interest in knowledge-repo :).
