### ISSUE TITLE
pandas.formats.style.Styler - Ipynb notebooks not working with Knowledge repo

### ISSUE THREAD

**Issue by Sundar0989** [airbnb/knowledge-repo#250]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi,

Thanks for this awesome product. I work with Data scientists and this tool is really useful to share the codes and outputs within our team. 

Recently, I tried to push a ipynb document which contains Pandas dataframe with styler formats (pandas.formats.style.Styler). When I run them, I can see the outputs formatted nicely, however once I push it to knowledge repo, I see the output gets messy.  Attached the screen shots with this 

Ipynb shot 1 - The output how it looks in jupyter notebook after I run it

![ipynb shot 1](https://cloud.githubusercontent.com/assets/8889346/24624210/15219c4e-1879-11e7-8d32-620e556d7f1c.PNG)

Ipynb shot 2 - The output how it looks after posting to Knowledge repo

![ipynb shot 2](https://cloud.githubusercontent.com/assets/8889346/24624209/15219870-1879-11e7-9ab7-5c2daa4ff307.PNG)

Please let me know if there is a work around for this. I really appreciate your help on this. Also, please let me know if you need any more details. Thanks.

Regards,
Sundar

**Comment by danfrankj** [comment]
Hey @Sundar0989 - thanks for your report. We've also run into this issue and have reported it to the pandas team. See issue: https://github.com/pandas-dev/pandas/issues/15651. They're planning to fix it in their next release. In the meantime, I've wrapped my styled dataframes with the following code. 

```
def plot_pandas_style(styler):
    """Currently pandas stylers have an unforatinate indent in the html they render
    See: https://github.com/pandas-dev/pandas/issues/15651

    Example
    -------
    plot_pandas_style(df.style.set_caption('this is my caption'))
    """
    from IPython.core.display import HTML
    html = '\n'.join([line.lstrip() for line in styler.render().split('\n')])
    return HTML(html)
```

Which should fix things until the next pandas release.

Hope that helps!
Dan

**Comment by danfrankj** [comment]
Closing - but feel free to re-open if you have questions

**Comment by Sundar0989** [comment]
Thank you. It worked..
