### ISSUE TITLE
Running the Web App from Directory

### ISSUE THREAD

**Issue by oanise93** [airbnb/knowledge-repo#251]
I just cloned the repo and am attempting to put an oauth workflow in the app. How would I go about running the web application from the directory containing the cloned code? 

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Hi @oanise93!

Great! We've been meaning (and still plan) to integrate better authentication choices into the knowledge repo, so it will be interesting to see how you go about it; and perhaps we can learn from it as we develop a generic solution.

The simplest way to bring up the development webserver is:
`knowledge_repo --debug --dev --repo <repo> runserver`
By default this will bring up a server on port 7000. Every time you make a code change, the server will automatically reboot.

Hope that helps!

**Comment by oanise93** [comment]
Thanks for the prompt reply. That's all I needed!
