### ISSUE TITLE
Add support for responsive HTML

### ISSUE THREAD

**Issue by Joaquimdcp** [airbnb/knowledge-repo#257]
Hello!

Is Knowledge-Repo responsive? (Can I use it on mobile phone?)

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Hi @Joaquimdcp!

Not yet! I'm working on it though! I have some local patches that are coming along. Should land reasonably soon, since it's blocking some other things we want to do.

Watch this space.

**Comment by matthewwardrop** [comment]
@Joaquimdcp This is remedied as of #292. Closing ahead of its being merged :).
