### ISSUE TITLE
Help needed to configure the extract_images_to_s3 postprocessor

### ISSUE THREAD

**Issue by tomsing1** [airbnb/knowledge-repo#273]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Thanks a lot for making this great tool available to the data science community.

I followed the installation instructions (on Mac OS 10.12.3 running python 2.7.12 via Anaconda) and am looking at my first knowledge repository now. 

Next, I would like to configure the `extract_images_to_s3` postprocessor. I have 
- downloaded the [extract_images_to_s3.py](https://github.com/airbnb/knowledge-repo/blob/master/resources/extract_images_to_s3.py) file linked in the [README.md](https://github.com/airbnb/knowledge-repo/blob/master/README.md) file
- customized it for my AWS S3 bucket
- and modified the `.knowledge_repo_config.py` file to contain `postprocessors = ['extract_images_to_s3']`

Now I am trying to figure out where to put my customized `extract_images_to_s3.py` file.
Can you give me a hint?

Thanks a lot,
Thomas

**Comment by matthewwardrop** [comment]
Hi @tomsing1 !

Glad to have you on board with the knowledge repo! 

Due to some Python magic, for the KnowledgePostProcessor subclass to be detected, it only needs to be loaded into memory... it doesn't matter how or where.

As such, you have two simple options regarding the extract_images python file:
1) import it into your knowledge repo config file
2) define the class **in** your config file

And that should be all it takes. Let me know if it doesn't work, but for now, I'll close down this issue.

And yes, documentation around this could be just a little better... but we'll get there.

**Comment by tomsing1** [comment]
Thanks a lot for the quick response, but I think I need a bit more help.
I tried the following, but so far without success:

I have
- added an empty `__init__.py` file to my `example_repo` directory
- downloaded the `extract_images_to_s3.py` file into the directory and edited the following two lines:
    - `S3_IMAGE_ROOT = 's3://XXXXX/images'`
    - `HTTP_IMAGE_ROOT = 'https://s3-us-XXXXX/images/`
- edited the `knowledge_repo_config.py` file: 
```py
from extract_images_to_s3 import ExtractImagesToS3

postprocessors = ['extract_images_to_s3']
```

I wasn't sure what the postprocessors list should contain, so I tried 'extract_images_to_s3' (with quotes), extract_images_to_s3 (without quotes) and ExtractImagesToS3 (without quotes). No exceptions were thrown in either case, but so far, none of the images in my posts have shown up on AWS S3. (There weren't any log messages referring to S3, either.) 

Finally, I verified that I can upload files from the command line using `aws s3 cp ...`, so my credentials are available and the default region is set.

**Comment by matthewwardrop** [comment]
Hmmm... interesting.

So just to be clear, the `postprocessors` configuration option specifies a list of identifiers for KnowledgePostProcessors (by name or class) that should be applied to knowledge posts on their way into the repository. It does not affect previously committed posts.

So just checking... you are running `knowledge_repo ... add ...` and not seeing the images on S3?

FWIW, the `__init__.py` file is not needed :).

**Comment by tomsing1** [comment]
Thanks again for the immediate response.
Yes, I have created new posts after specifying the postprocessor, but it doesn't seem to take effect.

Starting with the examples provided with the installation, I changed the title of the `example_post.Rmd` and executed the following command:

```bash
knowledge_repo --repo ./example_repo add ./example_post.Rmd -p project/another_post
```
When I start the server, the post is displayed correctly (including figures), but I don't think any interaction with AWS has taken place.

My `example_repo/.knowledge_repo_config.py` contains (omitting boilerplate):

```python
from extract_images_to_s3 import ExtractImagesToS3

postprocessors = ['extract_images_to_s3']
```

**Comment by matthewwardrop** [comment]
@tomsing1 One more quick question: Is the .knowledge_repo_config.py fully committed into the repository (including these changes?). This is required in order for it to be detected as the repository configuration.

**Comment by tomsing1** [comment]
Ah - that was part of the problem: I had not commited the `.knowledge_repo_config.py` file after making the change. Once I did, the import I had added took effect:

```python
from extract_images_to_s3 import ExtractImagesToS3
```
and I got the error message displayed below, because the module could not be found (the file was in the same folder as the config file). 

But when I copied the content of the `extract_images_to_s3.py` file into the `.knowledge_repo_config.py` file the upload to S3 was successful. 

```python
Traceback (most recent call last):
  File "/Users/sandmann/anaconda/bin/knowledge_repo", line 228, in <module>
    repo = knowledge_repo.KnowledgeRepository.for_uri(args.repo)
  File "/Users/sandmann/anaconda/lib/python2.7/site-packages/knowledge_repo/repository.py", line 46, in for_uri
    return cls._get_subclass_for(scheme)(uri, *args, **kwargs)
  File "/Users/sandmann/anaconda/lib/python2.7/site-packages/knowledge_repo/repository.py", line 76, in __init__
    self.init(**kwargs)
  File "/Users/sandmann/anaconda/lib/python2.7/site-packages/knowledge_repo/repositories/gitrepository.py", line 69, in init
    self.config.update(get_module_for_source(self.git_read(config.replace('git:////', '')), 'git_config'))
  File "/Users/sandmann/anaconda/lib/python2.7/site-packages/knowledge_repo/utils/exec_code.py", line 9, in get_module_for_source
    exec(source, module.__dict__)
  File "<string>", line 2, in <module>
ImportError: No module named extract_images_to_s3.py
```

I couldn't figure out how to successfully import the code from a separate file, but simply including it in the config did the trick. Problem solved! Thanks a lot 😄

**Comment by matthewwardrop** [comment]
Excellent! The remaining issues were likely due to path issues, and we should probably make all of this much clearer in documentation. The trouble is, of course, that things may change a little bit before we hit 1.0... but we should have this sort of thing nailed down shortly!

Thanks again for your perseverance!
