### ISSUE TITLE
Setting up users

### ISSUE THREAD

**Issue by rtjohn** [airbnb/knowledge-repo#276]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

My team has successfully deployed a knowledge-repo, and even written some ugly R and Python functions to make the addition and submission of knowledge posts simpler (never having to leave R or Python).  However, we are not seeing any documentation around getting users set up properly.  

Currently when someone comments it is submitted as an "knowledge_default".  Also, the comment is not sticking and goes away after refreshing the page or is never visible to anyone else using the web app.

Can we build some documentation around setting up users properly?  Is this existing functionality and I'm just doing something wrong (my current assumption) or is this not actually existing functionality yet?

**Comment by matthewwardrop** [comment]
Hi @rtjohn ,

Thanks for reaching out. Currently, we have not added support for managing authentication within the knowledge repo itself. For now, if users want authentication support, they must set up a proxying web server that adds authentication headers to the HTTP requests. You can then configure the username header in the server configuration, and by so doing effectively support users.

We do intend to add support for user authentication, which is tracked in #231 , so I'll close this issue in favour of that one.
