### ISSUE TITLE
Python 2.6 passing?

### ISSUE THREAD

**Issue by rtjohn** [airbnb/knowledge-repo#277]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

When I attempted to install knowledge-repo on a machine running CentOS 6.9 I ran into problems.
The issue appears to be related to the entrypoints package needing Python > 2.6:

```
Collecting entrypoints>=0.2.2 (from nbconvert[execute]->knowledge-repo[all])
  Could not find a version that satisfies the requirement entrypoints>=0.2.2 (from nbconvert[execute]->knowledge-repo[all]) (from versions: )
No matching distribution found for entrypoints>=0.2.2 (from nbconvert[execute]->knowledge-repo[all])
```

```
$ pip install entrypoints
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting entrypoints
  Could not find a version that satisfies the requirement entrypoints (from versions: )
No matching distribution found for entrypoints
```

The issue is resolved simply by upgrading Python to >2.6.  However, your CI tags on the repo say the Python 2.6 build is passing?

**Comment by matthewwardrop** [comment]
Thanks for the memo @rtjohn !

Python 2.6 used to be supported, but it looks like external dependencies no longer support it. While the core of the knowledge repo still supports Python 2.6, we would prefer not to maintain the knowledge repo for such an old version of Python, so we'll bump Python 2.6 from the list of supported versions.

Thanks again!

**Comment by matthewwardrop** [comment]
And done. Python 2.6 will no longer be officially supported as of the next published version!
