### ISSUE TITLE
Google charts - month indexing starts at 0

### ISSUE THREAD

**Issue by jeffreygrover** [airbnb/knowledge-repo#278]
Hi,

This is a _very_ minor thing, but I've noticed that the 'Stats' page uses Google charts. The months in JavaScript dates are 0-indexed, so all of the plots are off by a month. 

Thanks for creating and maintaining such a great tool!

-Jeff

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Thanks Jeff. We'll fix this for the next release :).
