### ISSUE TITLE
Problem with rendering of Links (signed URLs of files on S3)

### ISSUE THREAD

**Issue by durgakant** [airbnb/knowledge-repo#280]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
Hello, 
I am creating a python package for Listing signed URLs of different files inside a folder and its sub-folders available on S3, We just need to pass the path of the folder. It is same as what FileLinks function in IPython notebook does locally. The motivation is that It will allow the user to understand the data structure(folder structure) while going through a particular analysis and can open the relevant files to see the results. 
Suppose get_files() is a function which returns links of the files. 
In this case - the output on Ipython notebook looks like this:

command: get_files('ToNGJ/cdout_Cervicovaginal_Samples_Tampon_16s/bdiv_even24000/unweighted_unifrac_emperor_pcoa_plot/emperor_required_resources/css/images/')
Output: 
![git_issue2](https://user-images.githubusercontent.com/28943640/26871565-4b3f1806-4b91-11e7-837a-364acc033973.png)

The problem is that the Knowledge-repo doesn't render this Ipython ouput as it is. 
In Knowledge-repo for each link it appears like this( ie. it shows the HTML code for each link):  Also these links are not functional here. 

![akr_link](https://user-images.githubusercontent.com/28943640/26871469-e09500a6-4b90-11e7-81ae-2119caf04fe4.png)

What can be do to avoid this ? Also can these links be functional in Knowledge repo as well? 
Please Let me know...
Thanks

**Comment by matthewwardrop** [comment]
@durgakant Did you sort this out?

**Comment by durgakant** [comment]
Hey @matthewwardrop , 
No, not yet - I gave it a pause and was working on something else. 
Please let me know what can be done to resolve it ?
