### ISSUE TITLE
User Tracking for likes, comments

### ISSUE THREAD

**Issue by shashj199** [airbnb/knowledge-repo#283]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hey All,

We are using knowledge repo for our projects but one issue that we are facing is that comments are not getting saved, likes are not tracked. I know that there are other issues that talk about this so we went ahead and derived some clues to get this functionality working. We passed a server config file which points to a SQL database and we were able to save all the votes and comments on the database which was wonderful but if we want to track which user commented apart from knowledge_default then I understand that we have to implement a login feature. We started doing that by trying to insert a table in the SQL database (mainly for authentication) but were unable to do so. Is there another way to track users? How can we use AUTH_USERNAME_REQUEST_HEADER to pass user information to the web app? Forgive me if I sound vague but I am really interested in this project and to implement other functionalities like mails based on subscription for my organization. I am not that tech savvy but I am motivated. Please help me out. Thanks a lot.

**Comment by NiharikaRay** [comment]
Hi @shashj199!

Thanks for your interest in this project - the way we track users is by looking at the `AUTH_USERNAME_REQUEST_HEADER`, which we assume is a header passed in the request that contains the username of a specific user - code here: https://github.com/airbnb/knowledge-repo/blob/6b06ec1d41cde2ceff49419412e56adebecd03e4/knowledge_repo/app/app.py#L121

Is the a header that gets passed in when you make requests that contain user information?

**Comment by shashj199** [comment]
Hey @NiharikaRay,

Thanks for replying. We are trying to pass the header in the requests to the app. The way we are approaching this is by prompting a user to enter his username when he will try to open knowledge repo (sort of like login, but not that sophisticated), then once we have his username, we will save that in the browser's memory and pass that ```AUTH_USERNAME_REQUEST_HEADER``` through front end of your app. The first problem we are facing is to track from where the front end is making a request to flask backend for the username.

We might not be approaching this correctly, let me know if that is the case. 

Thanks a lot for your help.

**Comment by shashj199** [comment]
Hey @NiharikaRay,

We figured the above things out. Right now we have made an arrangement for open comments i.e. user can enter his information and then comment. We will try to implement login feature soon. Thanks for you help.

**Comment by matthewwardrop** [comment]
@shashj199 We now have mostly implemented an authentication scheme in #305. Closing this out in favour of it.
