### ISSUE TITLE
[Enhancement] Can prepare_app add methods to before_request

### ISSUE THREAD

**Issue by rahulravindran0108** [airbnb/knowledge-repo#285]
An easy way to get away with authentication is have prepare_app inject an authenticator before requests. Can this be done prepare_app using the KnowledgeFlask instance ? 

I really wanted a way to change set_user_information for custom auth.

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
@rahulravindran0108 Yes. The `prepare_app` function can do *anything* to the knowledge repo flask app. We are planning to add support for inbuilt authentication soon, which is tracked in #231.
