### ISSUE TITLE
Avoid Gunicorn deployer error in Windows

### ISSUE THREAD

**Issue by GonxoMR** [airbnb/knowledge-repo#289]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I am trying to install the knowledge repo in a windows machine and I got the next error when running the example:

`$ knowledge_repo --repo ./example_repo preview project/example_ipynbs`
WARNING:root:Gunicorn deployer is not available. It only works on POSIX platforms (e.g. Linux, Mac OS X, etc). If you are using a POSIX platform, please ensure that `gunicorn` is installed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\knowledge_repo", line 278, in <module>
    repo.set_active_draft(kp_path)  # TODO: Deprecate
  File "C:\ProgramData\Anaconda3\lib\site-packages\knowledge_repo\repositories\gitrepository.py", line 158, in set_active_draft
    self.config.published_branch = branch.name
AttributeError: 'NoneType' object has no attribute 'name'

I installed all dependencies with `$ pip install --upgrade knowledge-repo[all]`.
I know that Gunicorn is a Unix deployer but I don't know how to bypass its use. 

Thank you in advance.

**Comment by AndreaPisoni** [comment]
I see you closed the issue, how did you solve this?
