### ISSUE TITLE
Index/table of contents

### ISSUE THREAD

**Issue by GonxoMR** [airbnb/knowledge-repo#291]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hello everyone, 

is it there a feature that maps the knowledge_repo and presents an index/table of contents like post of page? If not does someone any ideas on how to approach this?

Thank you in advance, 
Gonxo

**Comment by matthewwardrop** [comment]
Hi @GonxoMR ,

Support for an interactive TOC was added in #292, as noted above. You can also add `[TOC]` to you document, which will be replaced with a generated table of contents. Once #292 is merged, you probably don't need a manually places TOC.

Hope that helps! Closing this out for now.

**Comment by GonxoMR** [comment]
Hello @matthewwardrop , 

thank you for your fast response and the addition of the features. That was awesome!

Although the TOC in every post is really handy and in a way can solve my problem. I was looking more to have a public index of the different post in the knowledge repo. The idea is to give any new visitor to the repo hint of which post to read first. 

Thank you for you time

**Comment by matthewwardrop** [comment]
Hi @GonxoMR ,

Is the idea here to have some manually curated list of posts as the main page of the site? Or do you have something else in mind?

Discoverability and searchability are definitely something we are working to improve in the next little bit. Is that what you mean here?

**Comment by GonxoMR** [comment]
Hi @matthewwardrop, 
sorry for the late answer, a few crazy days around here. 

I am not sure I am answering your question. I do not have an specific solution to the problem as I am pretty much dependent on you development. I will describe the situation and how I picture a possible solution.

Our knowledge repo has two main purposes:
- The first one is to share state of the art knowledge of our processes, what are we working on lately, results... This is pretty much solved by the temporal feature of the repo. 
- The second purpose, is to use it as three of knowledge. Some parts (a big chunk) of our knowledge is quite structured and invariant, that knowledge has the purpose of be share with the wider company, so we need in the home some kind of snapshot of the content of the repo and a way to direct the learning path (we can use links).
 
As a solution of this I got in my mind different solutions (not sure if they are practical ones):
- A fix post in the top of the home where we can map the knowledge with links to files. 
- An automatic index based in the location of the knowledge in the repo (the option -p while adding) that links to the posts. 
- Create another home where the post are fix in a given order, while maintaining a separated one for state of the art. 

In some sense I see how a curated selection  can help. 
Thank you for your time.

**Comment by matthewwardrop** [comment]
Hi again @GonxoMR,

One feature I'm planning to add soon is the concept of "series" or "collections", which consists of both ordered and unordered sets of posts. This sounds to solve most of your issues.

We are also looking to flesh out the index/feed page, allowing on the fly filters (which can include filtering down to particular path prefixes).

I also have a local patch that will soon be committed that allows site-specific overrides of templates and static resources, which would allow you to place a permanent link to certain collections or posts.

Taken together, I think most of your use cases will be catered for. Is there anything I missing?

M

**Comment by GonxoMR** [comment]
All this seems to work for me. Thank you for your time and nice work. :)
