### ISSUE TITLE
Add support for fetching updates to git repositories during index update

### ISSUE THREAD

**Issue by nherrero** [airbnb/knowledge-repo#295]
After deploying the knowledge_repo in a server we've seen that it needs to be restarted to display the new content pushed to the repo. Is this the expected behavior? Are we missing something? Thanks

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
@nherrero Currently, the knowledge repo does not update git repositories when it is running (largely because internally we run the knowledge repo on an isolated box and so this would fail). If you manually set up a cron job to update the git repository, however, it will pick up the changes. I will be adding support for automatic git pulls during the next week :).

**Comment by nherrero** [comment]
@matthewwardrop Great, we came up to the same solution, that of setting up a cron job for pulling from git. Not sure if setting up a git hook would do the trick. Anyway, thanks!!

**Comment by Joaquimdcp** [comment]
I had the same issue, and I solve it using a simple flask handler using github webhook. It is working very good. I don't know if you can solve it using the same way!

**Comment by jdavidheiser** [comment]
This is something we're looking forward to in a big way as we start spinning up our Knowledge Repo deployment in earnest.  Is there any ETA, or existing work I can help to polish up to get this ready to go?  Seems a bit silly to build some solution around cron as a stopgap if there's a better approach in the pipeline.

**Comment by matthewwardrop** [comment]
Well... I'm well past my initial ETA. Whoops! My dev hours have been divested substantially since then. But this isn't actually that challenging an addition, so I'll put up a PR this weekend to help you out, and tag you on it so you can test it out in your set up.

**Comment by matthewwardrop** [comment]
This is now implemented in #324.
