### ISSUE TITLE
Add support for downloading posts as PDF files

### ISSUE THREAD

**Issue by IreneRoma** [airbnb/knowledge-repo#298]
Hello again! 

I'm worried because users of my company need to export posts in **PDF** format. Until now it is only possible to download them as Rmd/ipynb/md or zip format.  
It would be great and quite simple to add this feature!

Thanks for this amazing tool
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by Joaquimdcp** [comment]
Wow! 
This would be fantastic @IreneRoma, in my  company we have the same issue!

**Comment by nickymikail** [comment]
Would something like Flask-WeasyPrint be the tool to use?

**Comment by matthewwardrop** [comment]
@IreneRoma I am actually already planning to add support for PDF downloading... but thanks for flagging this! Now I won't forget :).

**Comment by bulam** [comment]
@IreneRoma 
This feature has just been added with https://github.com/airbnb/knowledge-repo/pull/300. You can install the latest version of the knowledge repo from Github to enable it. I will be included in the next version release.
