### ISSUE TITLE
Visual glitch: "Collapse All Code" button overlaps with page stats (Chrome, Windows)

### ISSUE THREAD

**Issue by zerogjoe** [airbnb/knowledge-repo#303]
See image below:
![image](https://user-images.githubusercontent.com/29302451/28141653-de7e65c6-675d-11e7-9348-b96384677659.png)

Presumably introduced in https://github.com/airbnb/knowledge-repo/pull/297

OS: Windows 10 Home version 1607
Browser: Google Chrome 59.0.3071.115
Resolution: 1920x1080

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
This is a caching issue in the browser. If you waited long enough it would most likely disappear, but you can use `<ctrl> + <shift> + R` to force the browser to reload the cache. We'll work on solving this issue at some point using webpack or some such; but for now, closing this out. If hard refreshing the page does not solve the issue, please reopen :).
