### ISSUE TITLE
When adding a new post, error in Bash 'R' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by susanjo80** [airbnb/knowledge-repo#307]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
I was able to install the repo tools, set up SSH, download and install Git Bash and create a test post, but when I try to add that post to the repo I get the following error in Git Bash:
" 'R' is not recognized as an internal or external command, operable program or batch file."
Any idea what could be going on?
Here is the command I ran for reference:

$ knowledge_repo --repo ./insights_repo add test.Rmd -p Susan/test

Also attaching the full traceback:
![error](https://user-images.githubusercontent.com/7807917/28484989-bae859ac-6e3b-11e7-9906-58052ac99f1b.PNG)

**Comment by matthewwardrop** [comment]
Hi @susanjo80 ,

This looks similar to #46; but the short term solution (I think) is to run:
`set PATH=C:\Users\sjohnke\AppData\Local\Continuum\Anaconda3;C:\Users\sjohnke\AppData\Local\Continuum\Anaconda3\Scripts;%PATH%`

There's a way to add things to your path by default,  but I cannot remember how to do that in Windows.

Closing in favour of #46. Feel free to respond here or in #46 if this continues to be a problem.

**Comment by susanjo80** [comment]
Downloading the small program as suggested in #46 worked to resolve this for me. Thanks!
