### ISSUE TITLE
PyPDF2 not included in pip dependencies

### ISSUE THREAD

**Issue by dsimmie** [airbnb/knowledge-repo#31]
`PyPDF2` is not included in the pip dependencies so the following quick start line fails (if you don't have this library installed):

`knowledge_repo --repo ./example_repo preview project/example`

**Comment by matthewwardrop** [comment]
Thanks @dsimmie for looking into this. `PyPDF2` is supposed to be a soft dependency for those wanting to use PDF import support; but there was one lingering hard reference.

This is fixed in https://github.com/airbnb/knowledge-repo/pull/32.

Thanks again!
