### ISSUE TITLE
Include a Authentication Provider for LDAP

### ISSUE THREAD

**Issue by matthewwardrop** [airbnb/knowledge-repo#310]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by dorianbrown** [comment]
I've got an authenticator class for ldap working, but I'm not sure how to generalize the ldap query string as this can be pretty specific per organization. Any ideas on how to approach this?

**Comment by timkpaine** [comment]
+1

**Comment by kidtronnix** [comment]
Not sure if this helps, haven't had a chance to look at knowledge repo codebase yet...

https://github.com/apache/airflow/blob/master/airflow/contrib/auth/backends/ldap_auth.py

**Comment by naoyak** [comment]
Implemented in #553
