### ISSUE TITLE
Support for interactive visualizations

### ISSUE THREAD

**Issue by gthank** [airbnb/knowledge-repo#313]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

One of my users is reporting that plotly visualizations are not functional in the final post. Is this a known issue? Are other systems such as bokeh in Jupyter Notebooks working?

Regards,

Hank

**Comment by matthewwardrop** [comment]
Hi Hank!

This works in the latest master branch, but not in the current latest stable version (0.7.6). It was fixed in #259 . We'll launch a new version once some recent features are stabilised.

Best,
M
