### ISSUE TITLE
Google Oauth over https failing

### ISSUE THREAD

**Issue by jmmaxwell** [airbnb/knowledge-repo#318]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I'm trying to run the knowledge-repo with nginx over https and using google oauth. In order to get this to work I had to change this line:

`redirect_uri='http://{}/auth/login/{}/authorize'.format(redirect_url, self.name)`

to

`redirect_uri='https://{}/auth/login/{}/authorize'.format(redirect_url, self.name)`

However, now I just get the "You have insufficient permissions to access this resource" screen even though it appears that oauth is working. I'm not sure what to try next to fix this. Any suggestions?

**Comment by jmmaxwell** [comment]
Never mind, just needed to set the secret key.

**Comment by matthewwardrop** [comment]
@jmmaxwell Did you still need to change the url to the https protocol?

**Comment by jmmaxwell** [comment]
@matthewwardrop just got around to double checking that: I did still have to change the url to https
