### ISSUE TITLE
enable an update-in-place functionality for knowledge posts in a repo

### ISSUE THREAD

**Issue by jdavidheiser** [airbnb/knowledge-repo#327]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

This probably overlaps somewhat with the work in https://github.com/airbnb/knowledge-repo/pull/308, but I was hoping to discuss separately to see how I can help out.  A use case we've run into several times already is the need to update a bunch of source files all at once, and then update their knowledge repo posts.  As an example, say we decide to start using a new tag for all posts of a certain category, so want to go add that tag to the YAML headers in all of our posts.  Making copies of these posts one-at-a-time and updating them all is fairly tedious, so the ability to update in place, and push all of the changes with a single pull request, was desired.  Roughly speaking, the way I've done this has been:

- Check out the master branch of the knowledge repo
- Update any of the src/*.ipynb files that we need to make changes to
- create a new branch
- commit those updates
- run something similar to 
```import os
import knowledge_repo
repo = knowledge_repo.KnowledgeRepository.for_uri('~/sandbox/knowledge-repo/')
for diff in repo.git_diff(ref_base='master'):
     path = diff.b_rawpath
     if ".kp/" in path:
        post_path = path.split(".kp/")[0] + ".kp"
     if repo.has_post(post_path):
        post = repo.post(os.path.join(repo.path, post_path))
        modified_post = post.from_file(os.path.join(repo.path, path))
        repo.add(modified_post, path=post.path, update=True)
     else:
        print "no post found for modified file {}".format(path)
```

I guess I'm asking both whether this is a good approach, and whether the changes to managing knowledge posts will make these sorts of things easier.

**Comment by danfrankj** [comment]
Hey @jdavidheiser.

Thank you for your interest in KR and apologies we didn't get back to you quicker. Here's how I'd suggest you might go about the task of adding a tag to a set of posts. 

```
from knowledge_repo import KnowledgeRepository
repo = KnowledgeRepository.for_uri('~/path/to/knowledge')
for post in repo.posts():
    post.update_headers(tags=post.headers['tags'] + ['MYNEWTAG'])
    repo.add(post, update=True, message='adding new tag to ' + post.path)
    repo.submit(post.path)
    repo.accept(post.path)

    # these next lines are because the GitKnowledgeRepository currently
    # has not implemented a publish method 
    repo.git.git.checkout('new_tag_staging_branch')
    repo.git.git.merge(post.path)
    repo.git.git.push('origin', 'new_tag_staging_branch')
# finally open a pull request from new_tag_staging_branch to master 
```

**Comment by danfrankj** [comment]
I'll close this for now but please feel free to reopen there's still something unclear
