### ISSUE TITLE
Installing extras from git fails.

### ISSUE THREAD

**Issue by illiterate-stranger** [airbnb/knowledge-repo#330]
[Here](https://github.com/airbnb/knowledge-repo/blob/9ae7e4c652be824c83b6c8e92ac04591a291f02c/knowledge_repo/app/templates/about.html) and [here](https://github.com/airbnb/knowledge-repo/blob/5ba7e5eb20165e1bac24f85d8c5bf9c6233065ef/knowledge_repo/templates/repo_data_readme.md)

It mentions that the extras can be install with something like:

`pip install git+ssh://git@github.com/airbnb/knowledge-repo.git[some_extra]`

However, this fails for me with error:
`Command "git clone -q ssh://git@github.com/airbnb/knowledge-repo.git[all] /tmp/pip-i907kezo-build" failed with error code 128 in None`
Instead I propose to recommend `pip install git+ssh://git@github.com/airbnb/knowledge-repo.git#egg=project[some_extra]`

This works fine for me

For what it's worth, I tested this with pip 9.0.1 and python 3.6.2

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by danfrankj** [comment]
Fixed in https://github.com/airbnb/knowledge-repo/pull/335
