### ISSUE TITLE
Feature Request: Specify Custom Template File

### ISSUE THREAD

**Issue by jordan-wright** [airbnb/knowledge-repo#339]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

While the existing templates are nice in showing the different features available, I find myself having to delete large amounts of content before I can start writing. It would be ideal to specify the location of a custom template when calling the `create` [subcommand](https://github.com/airbnb/knowledge-repo/blob/master/scripts/knowledge_repo#L127).

An ideal command would look something like:

`knowledge_repo create --template path/to/template md test.md`

If there's interest in making this happen, I'd be happy to work on it and send up a pull req.

**Comment by matthewwardrop** [comment]
Greetings @jordan-wright, thanks for stopping by!

I think this is a good idea. I've started some work to improve user tooling in #308, and have added support for this as a goal. Combined with your comment on using Jinja variables for various features and a reasonable default context, I think this could definitely add value to the project. Feel free to submit patches for both of these things against the code in master (the code in #308 is a moving target and so I'll patch forward any changes you make).

**Comment by jordan-wright** [comment]
Ah, excellent work on #308! That looks like it'll provide all sorts of good improvements. Would you prefer I work from that branch and submit pulls reqs there instead of adding things to `master` here and putting you in a bind trying to make sure the changes your making will still work?

My goal is to put as little work on you as possible, so just let me know what's easiest for your workflow. 😄

**Comment by matthewwardrop** [comment]
The changes you are making are not deep in the fundamentals of the project, so I don't expect any issues. Feel free to just submit some patches to master. Porting the changes should be straightforward; and as mentioned, #308 is a moving target and everything is up for redesigns/etc.... that's nasty for patches. Moreover, for the next few releases at least (and probably until 1.0), we'll keep around the old `knowledge_repo` script anyway for compatibility, so the changes should be added there anyway.

**Comment by jordan-wright** [comment]
👍  Sounds like a plan, thanks!
