### ISSUE TITLE
Feature Request - expose the knowledge_repo script as functions/a class for easier integration

### ISSUE THREAD

**Issue by timkpaine** [airbnb/knowledge-repo#340]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I'm working on a plugin to integrate with jupyterlab, but have to manage the various commands [manually](https://github.com/timkpaine/knowledgelab/blob/master/knowledgelab/commands.py) to avoid making a subprocess call to the script. It would be nice to have them as standalone functions.

**Comment by matthewwardrop** [comment]
Hi @timkpaine. Thanks for working on this! Excited to integrate it into Jupyterlab, but have so far not been able to garner the time to work on it.

What kind of functionality do you need from the `knowledge_repo` script that is not already available in the API? Most of the code in the `knowledge_repo` script is just command line argument parsing, the rest being calls to code in the `knowledge_repo` python library.

**Comment by timkpaine** [comment]
@matthewwardrop Its all available in the API, I just need to parse the command file to figure out which calls to make. I suppose its less of a technical feature request than a documentation one, can combine into #65 if the calls made can have a little bit of documentation added around them to see what the args/kwargs do.

**Comment by matthewwardrop** [comment]
Aye... documentation is definitely a sore point... but we'll get there eventually :). If you have specific questions about what a method does, don't hesitate to reach out!
