### ISSUE TITLE
Add Login Message in "Insufficient Permissions" Handler

### ISSUE THREAD

**Issue by jordan-wright** [airbnb/knowledge-repo#366]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

When we distribute knowledge repo links to the team, if the team member isn't logged in, they are presented with the vague [flash message](https://github.com/airbnb/knowledge-repo/blob/72c6449e172a9a7bd4ed2337c3b2afa24c5cfc24/knowledge_repo/app/app.py#L133)

> You have insufficient permissions to access this resource.

We then have to explain how they need to login using the dropdown at the top right of the page.

What do y'all think about adding a bit more information here to explain to the user that they need to login with a valid account to view the post? A couple of options could be:

* Adding a login button below the flash message
* Simply appending "Please <login> to view the resource" with an href to /auth/login.

Happy to send a pull request with whichever route y'all want to take.

**Comment by aaronbiller** [comment]
@jordan-wright We were having similar feedback, I just made a PR with a fix for this: #370

**Comment by matthewwardrop** [comment]
Fixed with #370.
