### ISSUE TITLE
Running Knowledge repo on multiple backends

### ISSUE THREAD

**Issue by shashj199** [airbnb/knowledge-repo#375]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hey All,

I am trying to deploy multiple knowledge repos in one go. You have mentioned in your readme that it can be done. I tried using that method but it is kind of buggy. I don't see all the repos in web applications. The debugger sometimes shows that it has adjusted the paths of one repo while it doesn't do it for another one. I am using the following command for running it.

```
knowledge_repo --repo {name1}first-knowledge-repo/ --repo {name2}second-knowledge-repo/ deploy
```

Thanks a lot for your help

**Comment by matthewwardrop** [comment]
Hi @shashj199 ,

Thanks for letting us know about this, but so far I cannot reproduce your problem.

Can you try the following in a Python session:

```
from knowledge_repo import KnowledgeRepository
kr = KnowledgeRepository.for_uris({'name1': 'first-knowledge-repo', 'kr': 'second-knowledge-repo'})
for post in kr.dir():
    print(post)
```

Does that enumerate all of the posts in both repositories? If so, the problem may be that the same post exists in both repositories (as determined by UUID). If that is the case, then indexing may fail. We should probably fix that.

**Comment by shashj199** [comment]
@matthewwardrop I'm really sorry. I checked both the repos. One of the repo had nothing in the master branch. Once I had put something in the master, it worked perfectly. Closing the issue now.
