### ISSUE TITLE
New post not appearing in feed

### ISSUE THREAD

**Issue by martinapugliese** [airbnb/knowledge-repo#380]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I am following [the docs](http://knowledge-repo.readthedocs.io/en/latest/quickstart.html) in the part about creating new posts. My problem is I don't understand how to make the post appear in the homepage of the repo (feed). 

Initially I had changed the name of the folder to put posts into, naming it as `posts/`, but believing this would be the problem I've done the procedure again with `project`. No luck, the new post still does not appear. To my understanding after you `create` and `add` the post it should be there?

Note that `preview` works fine, I can see the post at its URL, just can't at the home level, so is something weird going on with indexing?

**Comment by martinapugliese** [comment]
ok, I've realised a new post appears in the feed only when you merge its branch into master! Closing this as solved then.

**Comment by glema-gpsw** [comment]
Hi,
I don't see any feed after the merge..
I'm running 
> knowledge_repo runserver
And in my branch master I have an example project project/example2:
as you can see in https://github.com/glema-gpsw/knowledge-base
Do you know why I can't see my post?
Thanks
