### ISSUE TITLE
ImportError: Bad git executable.

### ISSUE THREAD

**Issue by rpwils** [airbnb/knowledge-repo#385]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I am installing this on a AWS EC2 and encountered this when running knowledge_repo --version
any help?

ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

**Comment by rpwils** [comment]
think i got it

**Comment by matthewwardrop** [comment]
Great! Glad you sorted things out :). My guess, for posterity, is that you did not have git installed on this server instance.
