### ISSUE TITLE
Plotly in Rmd notebooks being published as images, not javascript

### ISSUE THREAD

**Issue by dorianbrown** [airbnb/knowledge-repo#387]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi guys,

I've been working on deploying a knowledge repo at my company, and since we're big R users we quickly ran into the issue that Rmd notebooks with Plotly doesn't work as expected. Since the converter uses knitr:
```r
"knit('{fname}', '{target_path}', quiet=F)
```
this tries to convert any plotly plots to static images. I think embedding the javascript plots would be preferable.

I've looked into how we could do this, and I've got some working code ready. I'll try and share it this week, but I've this would be my first contribution to a github project, so I'll need to figure that out first :grin:

**EDIT**: From what I've read, it seems I would need to be added as a contributor to the project in order to push my branch. Would that be possible?

**Comment by matthewwardrop** [comment]
Hi @dorianbrown,

Great! I'm more familiar with the Python side, where Plotly already works fine... so your patches will be more than welcome!

To contribute, simply fork the repository, and create a branch on your fork. You can then submit a pull request into this repository by following the instructions here: https://help.github.com/articles/creating-a-pull-request-from-a-fork/ .

Hope that helps!

**Comment by dorianbrown** [comment]
Very useful, PR has been made. Thanks!

**Comment by MeganBeckett** [comment]
Hi there, is this improvement going to be added? I am also using Knowledge Repo for an organization to share my reports, but the interactive plotly plots are rendered as static images. It would be really great if we could have this functionality.

Th same goes for datatables - these are also rendered as static images so one cannot filter, search, arrange, etc, as you would normally in an RMarkdown report.

**Comment by dorianbrown** [comment]
Hi Megan, this is my old pull request which had been forgotten. I might be able to take a look at it either this week or next week. 

With a little luck it might not need too much work to be ready for merging.
