### ISSUE TITLE
Willing to accept Username/PW Auth Implementation Patch Still?

### ISSUE THREAD

**Issue by nickbarnwell** [airbnb/knowledge-repo#408]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi,

I was peeking at #372 and saw @matthewwardrop was interested in a patch for Username/PW auth. Has any work on that started internally, or would you be happy to accept a 3rd party contribution?

Sorry for opening an issue to discuss something trivial - don't want to duplicate work!

**Comment by matthewwardrop** [comment]
Hi @nickbarnwell ! Patches are definitely welcome for inbuilt username / password auth. Essentially all of the backend work is done (model supports username / password), all that we need is the UI components that allow these to be set initially and authenticated against.

And don't worry about it being trivial :).

**Comment by nickbarnwell** [comment]
👍 . Got it, will try and get something out this week, thanks!
