### ISSUE TITLE
Support for GitLab as the basis for a Knowledge Repo?

### ISSUE THREAD

**Issue by connorshea** [airbnb/knowledge-repo#41]
I may be mistaken, but does Knowledge Repo have support for GitHub repos specifically or can you use it with any Git repo?

If the former, it'd be awesome to have support for Git repos agnostic of their origin. If the latter, the README should be clarified.

**Comment by matthewwardrop** [comment]
Greetings @connorshea!

The knowledge_repo supports any git repository; so it doesn't need to be tied to GitHub or GitLab. Feel free to use whatever git remote system makes sense to you!

I'll see that the README.md file gets updated :).

**Comment by connorshea** [comment]
Thanks! And thank you for open sourcing this, I've been interested in it since the original Engineering post about it :)

**Comment by matthewwardrop** [comment]
No worries. Thanks for your interest. One of my colleagues just updated the documentation, so this should be good now :).

Do let us know if you discover any other issues :).
