### ISSUE TITLE
Error when submitting

### ISSUE THREAD

**Issue by pveragen** [airbnb/knowledge-repo#429]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

We are experiencing a problem when submitting new posts. 
The add process works ok, and the new branches are created, but the submit raise this error: 

`ValueError: It does not appear that you have any drafts in progress for '<repo>/<project>/post.kp'.`

According to the code on gitrepository.py 

```
def _submit(self, path=None, branch=None, force=False):
        if not self.git_has_remote:
            raise RuntimeError("Could not find remote repository `{}` into which this branch should be submitted.".format(self.config.remote_name))
        if branch is None and path is None:
            raise ValueError("To submit a knowledge post, a path to the post and/or a git branch must be specified.")
        if branch is None:
            branch = self.git_branch_for_post(path)
        if branch is None:
            raise ValueError("It does not appear that you have any drafts in progress for '{}'.".format(path))
```

**Comment by pveragen** [comment]
The story continues.  

We created 2 new posts (the knowledge repo has only the first post), after having the previously described submitting problem both post were successfully submitted and the repo was merged. If I check the master, all folders are there. 
The actual problem is that those post aren't shown in the feed.   The only error i see on the terminal is this. 

```
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
ERROR:flask.app:Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/notebooks/shared/knowledge-repo/scripts/../knowledge_repo/app/index.py", line 51, in update_index_if_required
    update_index()
  File "/notebooks/shared/knowledge-repo/scripts/../knowledge_repo/app/models.py", line 143, in wrapped
    raise_with_traceback(e)
  File "/notebooks/shared/knowledge-repo/scripts/../knowledge_repo/app/models.py", line 138, in wrapped
    return function(*args, **kwargs)
  File "/notebooks/shared/knowledge-repo/scripts/../knowledge_repo/app/index.py", line 159, in update_index
    if post.uuid in kr_uuids:
TypeError: writable buffers are not hashable
```

**Comment by matthewwardrop** [comment]
Hi @pveragen! Sorry to hear you've been having troubles. These issues look very peculiar, and I have not been able to reproduce them here.

Which platform are you running this on? And which versions of Python 2.7 and knowledge_repo are you using? Hopefully we can get to the bottom of it for you.

**Comment by pveragen** [comment]
Hi @matthewwardrop , 

I'm running python 2.7 and knowledge_repo 0.8.1 
Also in the set up i'm using sqlite as database and flask as engine. Also using  github OAuth.

**Comment by pveragen** [comment]
Using the debug console 

```
>>> print kr_uuids
{'a3e50ab8-e279-4f70-aba3-a527a6334228': <knowledge_repo.post.KnowledgePost object at 0x7f6f497ad810>, 'cf3a2e82-c9e1-47b9-aa29-5e311e1b1641': <knowledge_repo.post.KnowledgePost object at 0x7f6f497ad110>, 'b8241de3-5b37-4943-8abd-231bd807e638': <knowledge_repo.post.KnowledgePost object at 0x7f6f497ad410>}
```

I suppose that means that all three post are on the index?

**Comment by pveragen** [comment]
it seems the problem was related to sqlite database. I removed the database and run the server and now is working and showing all the posts.

**Comment by matthewwardrop** [comment]
@pveragen Glad to hear that you sorted everything out! I'd still love to know why things were breaking for you, but with such limited time, I'll just be glad that everything worked out. Thanks for your patience, and for keeping us posted!

[And yes, if the uuids were in kr_uuids, then the posts are in the index.]

I'll close this issue out, but if this recurs, or you have further questions, don't hesitate to reopen the issue.
