### ISSUE TITLE
Github Authentication Error

### ISSUE THREAD

**Issue by Pixelartist** [airbnb/knowledge-repo#434]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hello,

I am currently in the process of setting / testing the knowledge repo (happy so far). While setting it up I  saw that there is an error while trying to oauth with github.

What I did:
- Installed latest version of knowledge-repo (Local version: 0.8.1_67dc8bf970e477b114dceb7cde870ed0b888bd96)
- installed by pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)

I created an oauth app in github and used the credentials within a config file I use for knowledge repo to start.
If I am authorizing the access to knowledge repo, it returns on the main screen with an error. The server responds with:

```
ERROR [flask.app] Exception on /auth/login/github/authorize [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/knowledge_repo/app/auth_providers/oauth2.py", line 159, in extract_user_from_api
    response_dict = json.loads(response.content)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/knowledge_repo/app/auth_provider.py", line 49, in authorize
    user = self.get_user()
  File "/usr/local/lib/python3.5/dist-packages/knowledge_repo/app/auth_providers/oauth2.py", line 143, in get_user
    return self.extract_user_from_api()
  File "/usr/local/lib/python3.5/dist-packages/knowledge_repo/app/auth_providers/oauth2.py", line 169, in extract_user_from_api
    raise RuntimeError("Failure to extract user information from:\n\n {}".format(response.content))
RuntimeError: Failure to extract user information from:

 b'{"login":"myloginname","id":22618842,"node_id":"MDQ6VXNlcjIyNjE4ODQy","avatar_url":"https://avatars2.githubusercontent.com/u/22618842?v=4","gravatar_id":"","url":"https://api.github.com/users/myloginname","html_url":"https://github.com/myloginname","followers_url":"https://api.github.com/users/myloginname/followers","following_url":"https://api.github.com/users/myloginname/following{/other_user}","gists_url":"https://api.github.com/users/myloginname/gists{/gist_id}","starred_url":"https://api.github.com/users/myloginname/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/myloginname/subscriptions","organizations_url":"https://api.github.com/users/ManuelAudibene/orgs","repos_url":"https://api.github.com/users/ManuelAudibene/repos","events_url":"https://api.github.com/users/myloginname/events{/privacy}","received_events_url":"https://api.github.com/users/ManuelAudibene/received_events","type":"User","site_admin":false,"name":"Manuel Mueller","company":null,"blog":"","location":null,"email":"mycompanyemail","hireable":null,"bio":null,"public_repos":0,"public_gists":0,"followers":0,"following":0,"created_at":"2016-10-04T14:37:32Z","updated_at":"2018-06-15T13:48:51Z"}'
```

I started digging and saw that @jordan-wright already mentioned these "bugs" in his upgrade log - https://github.com/airbnb/knowledge-repo/issues/402

Just starting with knowledge_repo it would be great if you could assist me to enable github oauth.

**Comment by pveragen** [comment]
There 2 issues with GitHub Oauth, 

first there is a bug on the parsing that affect python 3, but not to python 2.  
On python 2 you face a second issue . 

I applied the patch proposed here https://github.com/airbnb/knowledge-repo/issues/354 to oauth2.py 

  ```
def extract_from_dict(d, key):
      if isinstance(key, (list, tuple)):
          if len(key) == 1:
              key = key[0]
          elif d[key[0]] is None:
              return extract_from_dict(d, key[1:])
          else:
              return extract_from_dict(d, key[0])
      if isinstance(key, str):
          return d[key]
      raise RuntimeError("Invalid key type: {}.".format(key))
```
and worked ok

**Comment by ManuelAudibene** [comment]
I changed my oauth2.py as suggested but still see the error. I am currently trying to debug python, any help appreciated.

**Comment by Pixelartist** [comment]
I applied the suggested changes (directly on the server) but so far it did not change anything. Right now I am reading how to properly debug python to understand what actually causes the error - any help appreciated!

**Comment by pveragen** [comment]
did you switched from python 3 to python 2?  The error with python 3 is not solved with this patch. 
The issue was open some time ago but ir seems still havent been fixed. 


For Github Oauth there is still a problem on "extract_from_dict"

```
def extract_from_dict(d, key):
            if isinstance(key, (list, tuple)):
                if len(key) == 1:
                    key = key[0]
                else:
                    return extract_from_dict(d[key[0]], key[1:])
            if isinstance(key, str):
                return d[key]
            raise RuntimeError("Invalid key type: {}.".format(key))

```
the Github "Identifier" list of keys is of length 2 (['email', 'login']), so the else return a call to the same function with a d['email'] as first parameter instead of d. So the fix proposed by @harrdb12 works for github specific case. 

I hope this can help you

**Comment by Pixelartist** [comment]
Thanks you a lot! I had a little "derp" moment, I modified the source, realized that it is still running with python 3, kicked python 3, installed it again with 2 but forgot that this killed the manual patch.
I can confirm it is working now.
