### ISSUE TITLE
cannot update knowledge-repo

### ISSUE THREAD

**Issue by obtkhadija** [airbnb/knowledge-repo#438]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
Hi, i have done a git pull manually to update my knowledge-repo, but i can't see any changes.

**Comment by matthewwardrop** [comment]
Hi @obtkhadija ; I'm sorry to hear you've been having issues with the Knowledge Repo. Can you provide a little more context? What is your knowledge repo setup? Where did you do a git pull? How is your server configured?

**Comment by obtkhadija** [comment]
Hi @matthewwardrop, thank you for your reply. I'm using the latest version 1.0.8, configured with db postgresql as backend. I think that the problem come from the database, because the indexation work just fine without the backup.
