### ISSUE TITLE
Multiple slashes in Google authentication redirect_uri 

### ISSUE THREAD

**Issue by gustaver** [airbnb/knowledge-repo#442]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi, 

I'm getting multiple slashes in the redirect_uri when using Google authentication. I found that this bug was fixed in 285d93fa8dd511d45107ff04acb8d255558ee946. 

This seems to be causing issues with login, since the Google authentication is working (when adding the multiple slashes to the authorised OAuth redirect uris in Google Credentials), but redirecting back results in no actual sign in. The user is however written to the database. When setting ```SERVER_NAME = 'localhost:7000'``` in the config and running on localhost, the multiple slashes still appeared, but Google authentication worked fine and signed in the user. 

I see that this bug fix was committed after the latest release (0.8.1), is there any way to get this fix in my installation?  

Thanks for working on this great project, it's been very valuable for our team! 🐸

**Comment by matthewwardrop** [comment]
Hi @gustaver ! Thanks for your patience! I'll release a new version (v0.8.2) imminently, which should solve your problem.
