### ISSUE TITLE
Expose source files for download and/or linking in the web ui

### ISSUE THREAD

**Issue by jbwhit** [airbnb/knowledge-repo#45]
I was wondering if you had a system for sharing academic papers within the knowledge repo or do you use some different internal system? 

I'm thinking specifically if a notebook has references, and having a smooth way to link to them that gives not only the journal article itself, but perhaps a summary/relevant parts writeup somewhere else.

**Comment by NiharikaRay** [comment]
Internally, that hasn't been a use case for the knowledge repo, but there have been a few people who have manually created knowledge posts which are just lists with links to the academic papers as well as a short summary of what the academic paper is about. 

The linking is relatively straightforward - markdown supports links regardless - but being able to link to specific relevant parts is a little bit more tricky. We would need to be able to parse through the entire paper and if, for example, we were using section headers to specify certain sections, we'd need to be able to extract that specific section, all on render time. In addition, there's the security concern - how would we be able to access papers that are behind login screens?

That being said, I think this is an interesting use case. The Knowledge Repo traditionally has been to create and then curate content, but it's interesting idea to be able to curate already-created content.

**Comment by matthewwardrop** [comment]
@jbwhit Hello Jonathan! Long time no see. Hope things are well!

As @NiharikaRay said, we support Markdown links (along with pretty much all of the Markdown spec)... which sounds like the most basic implementation of what you might want. But I wanted to let you know of two other features which may be interesting to you.

1) You can attach multiple source files. If it makes sense in your institution to commit pdf articles directly into the repository, this the `knowledge_repo` command supports adding multiple source files to the repository along with the ipynb/Rmd source itself. Extracting them via the web interface is not presently possible, but definitely something we are planning to support.

2) In addition to standard external links, the knowledge repository supports intra-linking (using urls like "knowledge:projects/test.kp"). This could complement standard links to articles with internal links to write-ups about those articles.

Do you have a clear idea about how you might expect such a linking to work beyond this?

**Comment by jbwhit** [comment]
Been too long @matthewwardrop!

I don't have a clear idea of what I want, but I have a clear idea of what I think the problem is. A small team working on a consulting project (say), and they do research into visualization techniques on heart monitoring in medical literature. Between the 3-5 people they build up 20-30 papers within a week... each person storing the pdfs in their preferred format TITLE.Lastname.Pubyear.pdf vs PubYear-lastname.pdf vs default-name-from-journal.pdf. Syncing even this mini-library simply between team members becomes tedious and somewhat contentious almost immediately. 

There are, of course, solutions to simply storing the papers, Mendeley, or some other tool, but not everyone likes to use any particular tool -- but syncing any data on client laptops w/ a third party is often a no-go. So if there were an internal tool that could somehow solve that problem in an elegant way, I'd be happy. 

Further, I'm not wishing for some kind of fancy linking to specific parts w/in a paper (cool though that would be!). I'm wanting something simple enough for linking within documentation for clients, "Here is some claim, cited(awesome-paper2)" and **there being no barrier to pulling up that cited paper**. Linking pdfs by hand in markdown could work, but you have to hope against hope that people don't rename or move the pdfs, and that they are reading the docs from a git repo rather than on the web front-end of a knowledge repo.

Anyway, just a few thoughts of where I'm coming from and what I would make happen if I had a magic wand!

**Comment by matthewwardrop** [comment]
Seems like there's two issues here then:
1) Add support for linking to added src files. We currently support adding source files to the KnowledgeRepository backends; but there's no way to access them from the web ui. We need to fix that.
2) Add a way to "export" a knowledge post to a local file which can be shared with external parties, without giving them the entire repository; along with any linked source files (such as papers).

It is possible to add an idea of centralised data store/index, but it seems to me that this is needlessly complicated. If we got around to adding the above features, would that be sufficient for you?

**Comment by jbwhit** [comment]
Interesting, you took it in a different direction than I was expecting...

So the first one, yes definitely, would be very helpful.

The second one, I'll have to think about it. I wasn't imagining a budding off from the main knowledge repo, I was imagining running a dedicated client knowledge repo that would have all relevant notebooks/analysis/references for the client as one web-interface. It would be entirely self-contained behind their firewall (or whatever).

**Comment by matthewwardrop** [comment]
Excellent. I'll change the name of this issue to reflect this first feature addition.

If the latter idea is useful, feel free to open up a second issue :).

**Comment by matthewwardrop** [comment]
@jbwhit At long last, this is done. You can now download any files added to the knowledge post as of #292. Referencing of external material still best done in via free-form markdown links. I'm planning on adding support for academic style references soon; but that will still not embed the PDFs themselves. You can manually embed the PDFs by referencing them as "src" files when adding the knowledge post (or by adding them to the repository manually under "orig_src").

**Comment by jbwhit** [comment]
Thanks Matthew!

--
Jonathan Whitmore, PhD
Web: JonathanWhitmore.com <http://jonathanwhitmore.com/>
US (Google Voice): +1 (321) 252 9448
