### ISSUE TITLE
Bug in Auth_providers that won't let you sign in the Knowledge Repo App

### ISSUE THREAD

**Issue by YolaK** [airbnb/knowledge-repo#468]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

I would like to bring your attention to an issue I figured out with respect to the knowledge repo app:

I used Github OAuth authentication to allow different users sign in the app by redirecting them to their Github account. When I pressed the sign in button, although I would get redirected to my Github account, I didn't get redirected and signed in the app. After some research, I managed to solve the problem by making a small change in "..../knowledge_repo/app/auth_providers/oauth2.py", in line 32, where I switched 
'identifier': ['email', 'login'] 
to 
'identifier': ['login'].

The problem seemed to be caused by the fact that function "extract_from_dict" expected to find email and login in a nested form, while that's not the case for the Github OAuth authentication as can be seen here (https://developer.github.com/v3/users/#get-the-authenticated-user):
![image](https://user-images.githubusercontent.com/24662570/47597211-755e0e00-d941-11e8-8048-f7e619bbdb6d.png)

Changing line 32 bypasses this problem by only looking for the one of the two fields, but a more robust solution would be to update the extract_from_dict function in a way that it will expect the requested fields in both nested and not nested forms, so that all kinds of authenticators can be utilized, independently of the exact way with which they store users information.

**Comment by alps2677** [comment]
Hi,

I was updated auth provider in config_defaults.py, But changes not apply, can you please explain me how do I setup auth provider.
