### ISSUE TITLE
Plotly does not work

### ISSUE THREAD

**Issue by glema-gpsw** [airbnb/knowledge-repo#470]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
Hi,
I am using your example for a notebook with plotly: https://github.com/airbnb/knowledge-repo/blob/master/tests/test_posts/plotly.ipynb
 but the server is not rendering any plot..
Using the inspect option in my browser in the console I get: 
```
Uncaught TypeError: Plotly.newPlot is not a function
at test2.kp:245
```
 It does however work when I launch it as a jupyter notebook.

Thanks

**Comment by amniskin** [comment]
I know this is older than time itself, but can you update nbconvert and re-test it?

**Comment by apaillarse** [comment]
Does anyone managed to find a workaround to make plotly work?

**Comment by mazzma12** [comment]
> Does anyone managed to find a workaround to make plotly work?

Still looking for it

**Comment by amniskin** [comment]
The newest version of nbconvert fixes this issue

**Comment by mazzma12** [comment]
> The newest version of nbconvert fixes this issue

thanks for the fast reply. Do you know if it shall be done on the client side or server side ?

**Comment by amniskin** [comment]
Wherever you’re adding the notebooks to the repo.
