### ISSUE TITLE
documentation --update missing -p parameter

### ISSUE THREAD

**Issue by WesleyTheGeolien** [airbnb/knowledge-repo#479]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
The documentation command to update a post is missing the `-p` parameter in the command line string : `knowledge_repo --repo <repo_path> add --update <file with format {ipynb, Rmd, md}> <location in knowledge repo>` which throws an error `knowledge_repo: error: unrecognized arguments:`

I propose the string should be `knowledge_repo --repo <repo_path> add --update <file with format {ipynb, Rmd, md}> -p <location in knowledge repo>`

Pull request 480 : https://github.com/airbnb/knowledge-repo/pull/480

**Comment by matthewwardrop** [comment]
Thanks for the patch. Fixed in your PR (#480).
