### ISSUE TITLE
knowledge repo content refresh

### ISSUE THREAD

**Issue by qthurier** [airbnb/knowledge-repo#48]
The only way I found at the moment to have a content up to date served by the webapp is to stop it and redeploy it. Is there a workaround to get a fresh content, like could we force the webapp to refresh the content every x hours?

**Comment by NiharikaRay** [comment]
Hi! Currently there isn't, but we're working on a feature to allow the user to hit an `/update` endpoint to update the content, and we hope to have it out shortly!

**Comment by qthurier** [comment]
Awesome thanks for the reply.

**Comment by matthewwardrop** [comment]
Hi @qthurier; we have finally addressed this in #105 . Should be merged soon.

**Comment by matthewwardrop** [comment]
This is now fixed in master. Will be part of the next release :).
