### ISSUE TITLE
Latex formulas not rendering in html

### ISSUE THREAD

**Issue by precabal** [airbnb/knowledge-repo#481]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

When rendering an iPython notebook which contains latex equations, they are not rendered and instead they are displayed as raw latex code. 

I'm guessing this is related to the following nbconvert issue:

https://github.com/jupyter/nbconvert/issues/925#issuecomment-448040303

Is anyone else running into this?

**Comment by matthewwardrop** [comment]
@precabal I haven't run into this personally yet, but we'll probably want to bump the MathJax version soon anyway, which seems like it might help here. Could you try bumping the mathjax dependency in knowledge repo and see if that helps? [If you need help doing this, let me know].

**Comment by precabal** [comment]
Yes! I'd be very happy to contribute to the project, though I'd appreciate some directions since this would be my first real contribution to OSS. 

My understanding so far is that I first need to fork the project, then try updating the dependency (where in the code?), then installing via `python setup.py install`, and then trying out how my latex formulas are rendered. If the problem is fixed, open a pull request... so far so good?
