### ISSUE TITLE
using emojis in markdown cells raises errors about headers

### ISSUE THREAD

**Issue by benlawson** [airbnb/knowledge-repo#483]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

When there is an emoji in a markdown cell in my document, I get the following error:
```
RuntimeError: Knowledge post is missing required headers {'title', 'tldr', 'created_at', 'authors'}. Please rerun this operation in interactive mode, or add headers manually to the post source file.
```

This error doesn't make sense as the headers are not missing. 

simple example created with `knowledge_repo create ipynb test.ipynb` then pasting an emoji in

![image](https://user-images.githubusercontent.com/7769994/50296124-b48f7380-0447-11e9-935f-1ce537a77d1d.png)

The first markdown block is changed to this:
```
*NOTE: In the TL,DR, optimize for **clarity** and **comprehensiveness**. The goal is to convey the post with the least amount of friction, especially since ipython/beakers require much more scrolling than blog posts. Make the reader get a correct understanding of the post's takeaway, and the points supporting that takeaway without having to strain through paragraphs and tons of prose. Bullet points are great here, but are up to you. Try to avoid academic paper style abstracts.*

 - Having a specific title will help avoid having someone browse posts and only finding vague, similar sounding titles
 - Having an itemized, short, and clear tl,dr will help readers understand your content
 - Setting the reader's context with a motivation section makes someone understand how to judge your choices
 - Visualizations that can stand alone, via legends, labels, and captions are more understandable and powerful
 - 😊
```

**Comment by matthewwardrop** [comment]
@benlawsom I suspect this is due to the emoji causing the document to be unicode encoded; and that previously it was assumed that the only error (or certainly most common error) that could happen during yaml parsing would be due to missing headers. I'll investigate this, but in the mean time, using Python 3 for your `knowledge_repo` installation should resolve this. Can you confirm?

**Comment by benlawson** [comment]
I believe I'm using python3 for my knowledge repo. The following install gets the same error with the `test.ipynb` I posted.

```bash
$ which pip
/home/ben/anaconda3/bin/pip
$ pip --version
pip 18.1 from /home/ben/anaconda3/lib/python3.6/site-packages/pip (python 3.6)
$ pip install knowledge_repo[all]
....
$ which knowledge_repo 
/home/ben/anaconda3/bin/knowledge_repo
```

Thanks for taking a look! We ended up removing emjois from the post, but I wanted to make sure it was documented in case someone else ran into the error
