### ISSUE TITLE
Post header parsing fails with windows-style (CRLF) line endings

### ISSUE THREAD

**Issue by dafrose** [airbnb/knowledge-repo#489]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi and thank you very much for this amazing project. I tried it out today ran into errors. After several attempts to resolve them (and starting to write issues), it boiled down to this:

### Problem

When files are comitted with windows-style (CRLF) endings, the web app is unable to render (or even find) the post. The previewer (`knowledge_repo --repo <repo-path> preview <post-path>`) fails when looking for the YAML header with the following error:

```
ValueError: YAML header is missing. Please ensure that the top of your post has a header of the following form:

---
title: "This is a Knowledge Post title, quoted so we can use special characters like ':'"
authors:
- sally_smarts
- wesly_wisdom
tags:
- knowledge
- example
created_at: 2016-06-29
updated_at: 2016-06-30
thumbnail: 2
tldr: |
    You can write any markdown you want here (the '|' character makes this an escaped section)

    * bullet
    * bullet

    You can even write arbitrary html (html is valid markdown)
    <table>
    <tr>
    <th>hi</th>
    <th>I'm </th>
    </tr>
    <tr>
    <td>a</td>
    <td>table</td>
    </tr>
    </table>
---
```

which misleadingly lead me to try and modify the header. Interestingly enough, this happened only with a defined remote for the git repo. When I added a post with no remote defined for the repo, everything worked as expected. 

### Solution

As it turned out, the parser expects unix-style (LF) line endings and breaks on windows-style (CRLF) line endings. The recommended way to use git on windows is "checkout as windows-style, commit unix-style" which corresponds to `git config core.autocrlf true`. Manually changing the line endings (using PyCharm) and enforcing unix-style line endings everywhere (`git config core.autocrlf input` and adding this [.gitattributes](https://github.com/airbnb/knowledge-repo/files/2728611/gitattributes.txt) to the repo solved the issue. (I did not retry both ways independently.)

For some reason this was not necessary with a local-only repo. This would make sense, if files are committed LF locally by default, but checked out as CRLF when pulling from the remote repo. Does this happen? 

Either way, as it seems, CRLF line endings pose a problem and I wanted to tell you about it ;-)

**Comment by matthewwardrop** [comment]
Thanks @dafrose . This sounds like a good opportunity for a simple patch. Interested in submitting one?
