### ISSUE TITLE
Cannot view tags page anonymously

### ISSUE THREAD

**Issue by alexlatchford** [airbnb/knowledge-repo#493]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
![screencapture-10-79-20-231-8889-tag_pages-2019-01-31-16_02_45](https://user-images.githubusercontent.com/628146/52093878-a9b11e00-2571-11e9-9db5-85aeb3244f83.png)

We have everything set to view anonymously as we're running with a git backend and don't want to take on a DB dependency/auth dependency yet. Would be great to be able to view all posts for a given tag anonymously! 

Looks like there are a bunch of `POLICY_ANONYMOUS_*` config settings but there is no option for tags :)

Keep up the great work!

**Comment by matthewwardrop** [comment]
Thanks for flagging this @alexlatchford. Want to contribute a patch?

**Comment by tkocmathla** [comment]
I added a patch that addresses this. It works for me, but let me know if there are other changes needed.

**Comment by bulam** [comment]
Thanks for flagging @alexlatchford and @tkocmathla for contributing a fix. I tested, updated and merged the fix https://github.com/airbnb/knowledge-repo/pull/506

It will be included in the next release. In the meantime, you can install the updated version from github directly.
