### ISSUE TITLE
Research oriented question about data science notebook sharing

### ISSUE THREAD

**Issue by mkery** [airbnb/knowledge-repo#495]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
Hi there! I'm an researcher from Carnegie Mellon University and am putting together a study on best-practices for peer review of data science notebooks & sharing notebooks. Would you perhaps be willing to chat about your experience getting this knowledge sharing platform underway at Airbnb? From what I've found so far, Airbnb is really unusual in open-sourcing and publishing blogs on this kind of notebook quality and knowledge sharing platforms, so it would be fascinating to hear if your team has some lessons-learned or strategies in your experience of nudging people towards more sharable data science work. 

I can be reached at mkery@cs.cmu.edu! Sorry to pester. You can check out some of my prior studies on notebooks in this paper [(The Story in the Notebook)](https://marybethkery.com/projects/Verdant/Kery-The-Story-in-the-Notebook-Exploratory-Data-Science-using-a-Literate-Programming-Tool.pdf) as well as others on my page https://marybethkery.com/.

Thanks!
mkery

**Comment by matthewwardrop** [comment]
Hi @mkery, I no longer work at Airbnb, and I came into the project later on in the development cycle. @NiharikaRay is your best bet, and it looks like she is a Carnegie Mellon University alumnus!
