### ISSUE TITLE
Auth Provider with GitHub

### ISSUE THREAD

**Issue by alps2677** [airbnb/knowledge-repo#510]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj
I was try to GitHub as auth provider, when updated auth provider in config_defaults.py, changes not apply when I start server, can you please tell me what I am missing.

**Comment by bulam** [comment]
Hi @alps2677 Could you tell us a bit more about your set up environment? It would help debug this issue
