### ISSUE TITLE
Get original ipython notebooks

### ISSUE THREAD

**Issue by shashj199** [airbnb/knowledge-repo#512]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

We sometimes continue the work of other colleagues using knowledge repo. One difficulty that we always face is that the ipython notebook in KR does not contain the outputs (they have been separated into md and ipynb). This means that we have to run others' notebooks again in order to get the outputs. Sometimes it can be tedious. Is there a way in KR to get the original intact ipython notebook? I know of ways like notedown which can be used to do it but since images are separated in KR as well, notedown doesn't work perfectly. 

Thanks a ton

**Comment by bulam** [comment]
Hi @shashj199 Sorry about the delay. We have a feature for this use case actually.

If you want to contribute additional files to your Knowledge Post, like .sql query files, small datasets, trained models or in your case intact Jupyter notebooks with their outputs, you can use the option `--src <file1> <folder1> <file2>...` which adds additional source files to your knowledge repo project. As you know, the jupyter notebook without the outputs is already automatically included, but you could add the jupyter notebook with outputs as an additional source file in this.

I will make sure to include this in the updated documentation.
