### ISSUE TITLE
Unicode error while adding new notebook to repo

### ISSUE THREAD

**Issue by IntuitionMachine** [airbnb/knowledge-repo#513]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

INFO:knowledge_repo.post:YAML header is incorrectly formatted or missing. The following information may be useful:
unacceptable character #x001b: special characters are not allowed

This happens across many notebooks.  

Works for version 0.7.3 but not 0.8.3 to 0.8.8

**Comment by bulam** [comment]
Sorry about the delayed response. Could you provide some example text and ideally the characters that trigger this issue?

**Comment by naoyak** [comment]
Looks like this is by design. https://github.com/yaml/pyyaml/issues/397
