### ISSUE TITLE
Custom KnowledgePostProcessor with new yaml config

### ISSUE THREAD

**Issue by vrtsig** [airbnb/knowledge-repo#514]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hi.

First of all: thanks for the great work!

I was wondering whether it is still possible to use a custom `KnowledgePostProcessor` without forking knowledge_repo and adding it to `/postprocessors/`, directly. Reading through the source code and documentation it seems to me that the way these were detected was very much dependent on an instance of `SubclassRegisteringABCMeta` being created/imported in the old `.knowledge_repo_config.py`.

Thanks!

**Comment by bulam** [comment]
Hi @vrtsig I think you might have to fork the repo to do this, but you also welcome to submit your custom processor and we can merge it into the master.
