### ISSUE TITLE
Refresh the docs on readthedocs

### ISSUE THREAD

**Issue by omrihar** [airbnb/knowledge-repo#519]
I've been trying out knowledge-repo and came across multiple problems that seems to have resulted from following the old documentation on knowledge-repo.readthedocs.io. Looking through the issues it seems that several PRs modified the docs, but the changes didn't propagate yet to the documentation website. It might be a good idea to synchronize the two, so that new users can have a lower entrance barrier to knowledge_repo.

Except for that - thanks for creating this cool project open source :) If we end up using it I'll try to contribute back (if we have something to contribute!).

**Comment by bulam** [comment]
Thanks for reporting this. I'm working on fixing the Read the Doc sync

**Comment by bulam** [comment]
Sorry didn't mean to close before this. The docs are updated now at https://knowledge-repo.readthedocs.io/en/latest/
