### ISSUE TITLE
Intra-linking format

### ISSUE THREAD

**Issue by qthurier** [airbnb/knowledge-repo#53]
Could you elaborate on how to point from a notebook/md file to the ressources in orig_src?
 
Let's say my knowledge repo is foo, my project is bar, my post is post. What url should I use in order to render an image? I've tried to copy the format suggested in #45 but this doesn't work:

`![text](foo:bar/post.kp/orig_src/ressource.png)`

**Comment by earthmancash** [comment]
Hello Quentin! We currently only have intra-linking at a post level. So if you have a post in path `projects/growth/test.kp`, you can link to that post with a simplified `knowledge:projects/growth/test.kp`. We are planning on building the ability to link to files in `orig_src`, but don't have it built currently. It's definitely functionality we'd like to support, as part of https://github.com/airbnb/knowledge-repo/issues/45.

**Comment by earthmancash** [comment]
@qthurier or perhaps I misunderstood. Are you trying to contribute a post that has an image link to something local on your computer, and you want that image to render on the site? That should be working, are you seeing broken images?

**Comment by qthurier** [comment]
The use case is that I want to be able to display an image with the markdown syntax, but I don't know what path I should use:

`![text](foo:bar/post.kp/orig_src/ressource.png)`

**Comment by earthmancash** [comment]
Images from the contributed posts will either get put in the images/ folder of a kp, or pushed to a cloud hosting service such as s3 if that is configured. The logic for that process is here:

https://github.com/airbnb/knowledge-repo/blob/master/knowledge_repo/postprocessors/extract_images.py#L33

So after running `knowledge_repo add` on the post, the image paths should change to the kp location. Is that not happening for you?

**Comment by qthurier** [comment]
let's say this is my markdown file:

![screen shot 2016-10-12 at 12 33 35 pm](https://cloud.githubusercontent.com/assets/4801331/19292387/3c964628-9078-11e6-9202-b090339b668b.png)

this is what the web app looks like:
![screen shot 2016-10-12 at 12 35 07 pm](https://cloud.githubusercontent.com/assets/4801331/19292438/8ad77d48-9078-11e6-9f7f-ee268b79da01.png)

because the html source code still point to my local path:
![screen shot 2016-10-12 at 12 37 03 pm](https://cloud.githubusercontent.com/assets/4801331/19292452/b0d61fd6-9078-11e6-99a8-a3004bd72891.png)

**Comment by earthmancash** [comment]
Interesting, I just ran through the process on the Rmd field with a local image reference to make sure the images are getting byte encoded, which is what the repo does if there's no cloud hard drive to put it on. 

Here's the markdown reference:

![image](https://cloud.githubusercontent.com/assets/20175104/19293809/4badf454-8fdc-11e6-83b9-1aa0ff75ee65.png)

and here's the preview:

![image](https://cloud.githubusercontent.com/assets/20175104/19293801/3dbf8cc2-8fdc-11e6-9095-7865e12464ad.png)

Can you send me the output from running the add command, including the add call?

**Comment by earthmancash** [comment]
Here's a fix for the issue

https://github.com/airbnb/knowledge-repo/pull/59

**Comment by qthurier** [comment]
I've tested the branch tilde-local-image-paths and the html source code is still calling the local path

**Comment by earthmancash** [comment]
Did you create a new knowledge data repo using the branch? Adding gitposts uses the post contribution code from the `.resources` folder of the data repo.

**Comment by qthurier** [comment]
Ok thanks, it works perfectly with python 2.7, not with 3.5 that raise error now when adding md post, but seems to be another issue.

**Comment by earthmancash** [comment]
Great, I see the other issue with byte encoding local images on python 3.5, will have a look. Thanks for filing these issues!

**Comment by GonxoMR** [comment]
Hello @earthmancash, 

is there any development on this front? We are having the same issue as @qthurier. 

Thank you in advance
