### ISSUE TITLE
'knowledge_repo' is a package and cannot be directly executed'

### ISSUE THREAD

**Issue by anjalijain22** [airbnb/knowledge-repo#530]
When I try to create a ipython notebook using the command - 
python -m knowledge_repo --repo "C:/User/Anjali/Desktop/Knowledge_Repo" create ipynb example_post.ipynb
 
I get the following error -
No module named knowledge_repo.__main__; 'knowledge_repo' is a package and cannot be directly executed

Can someone please help me out with this issue?

**Comment by bartaelterman** [comment]
Drop the `python -m`.
See https://knowledge-repo.readthedocs.io/en/latest/installation.html

**Comment by bulam** [comment]
@bartaelterman 's suggestion should work, so closing this one.
