### ISSUE TITLE
ImportError: cannot import name url_encode

### ISSUE THREAD

**Issue by kelvins** [airbnb/knowledge-repo#531]
I'm facing the following error when trying to run `knowledge-repo==0.8.8`.

`knowledge_repo --repo . runserver --config config.py --port 7000`:

```bash
Traceback (most recent call last):
  File "/home/kelvins/luizalabs/heisenberg/venv/bin/knowledge_repo", line 300, in <module>
    from knowledge_repo.app.deploy import KnowledgeDeployer, get_app_builder
  File "/home/kelvins/luizalabs/heisenberg/venv/lib/python3.6/site-packages/knowledge_repo/app/__init__.py", line 4, in <module>
    from .app import KnowledgeFlask
  File "/home/kelvins/luizalabs/heisenberg/venv/lib/python3.6/site-packages/knowledge_repo/app/app.py", line 20, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode'
```

It seems `knowledge-repo` [does not pin the Werkzeug version](https://github.com/airbnb/knowledge-repo/blob/master/knowledge_repo/_version.py#L39) and Werkzeug has released a new version 1.0.0 that breaks the retro compatibility (issue: https://github.com/pallets/werkzeug/issues/1714).

```bash
$ pip show werkzeug

Name: Werkzeug
Version: 1.0.0
Summary: The comprehensive WSGI web application library.
Home-page: https://palletsprojects.com/p/werkzeug/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD-3-Clause
Location: /home/kelvins/luizalabs/heisenberg/venv/lib/python3.6/site-packages
Requires: 
Required-by: knowledge-repo, Flask
```

**Comment by bartaelterman** [comment]
Maybe you can suggest a PR? It seems to be here: https://github.com/airbnb/knowledge-repo/blob/master/knowledge_repo/_version.py#L39

**Comment by wrgoldstein** [comment]
👍  I'm having this issue too

**Comment by gmwill92** [comment]
Is there a fix for this?

**Comment by bartaelterman** [comment]
As long as there is no maintainer responding I think your best option is to clone this repository locally, make the modifications from @kelvins [pull request](https://github.com/airbnb/knowledge-repo/pull/532) and install locally.

**Comment by kelvins** [comment]
@gmwill92 another workaround would be to pin the Werkzeug version in your requirements/Pipfile:

```
knowledge-repo[all]
werkzeug==0.16.1
```

**Comment by toruhitomi** [comment]
I had the same issue and manually fixed it by modifying two files:

1. site-packages/knowledge_repo/app/app.py (line 20)
    from werkzeug import url_encode --> from **werkzeug.urls** import url_encode

2. site-packages\knowledge_repo\app\routes\editor.py (line 9)
    from werkzeug import secure_filename --> from **werkzeug.utils** import secure_filename

**Comment by kelvins** [comment]
I believe this issue was fixed by PR https://github.com/airbnb/knowledge-repo/pull/537, so I'm closing it.
