### ISSUE TITLE
Key error when specifying LDAP authentication

### ISSUE THREAD

**Issue by antchau** [airbnb/knowledge-repo#568]
Hello,

I am trying to configure LDAP authentication for our knowledge repo but am getting a `KeyError: 'ldap'`. From reading the documentation and some related issues, I believe I had to specify 'ldap' in AUTH_PROVIDERS as well as supplying values for LDAP_SERVER and LDAP_USERDN_SCHEMA. I have specified all of these but am running into the key error. Is there anything I'm missing to setup LDAP?

**Comment by bulam** [comment]
Hi @achau713 Just to clarify, are you doing `pip install` or installing from the git repo? The git repo is multiple commits ahead and has some fixes for LDAP authentication

**Comment by achau713** [comment]
Hi @bulam. We did do a pip install on our internal server. That is probably the issue. We will try installing straight from the git repo. Thanks!
