### ISSUE TITLE
Where is the collapse code button?

### ISSUE THREAD

**Issue by franciscogmm** [airbnb/knowledge-repo#581]
I can't find the collapse code button. Is this in an unpublished build? I'm using the latest version on pypi: knowledge-repo 0.8.9

**Comment by bulam** [comment]
@franciscogmm The button should still be present. Have you tried hovering on the right edge of the code chunk?

If you still can't see the button, you can try installing from the git repo. That one has new updates that are not in the pip version yet. In the git version, the button looks like this.
<img width="232" alt="Screen Shot 2020-10-13 at 6 51 28 PM" src="https://user-images.githubusercontent.com/8813413/95934196-25262380-0d85-11eb-8b5b-9408742ce3fe.png">
