### ISSUE TITLE
bug: running web app on v0.6.5

### ISSUE THREAD

**Issue by nathancomiskey** [airbnb/knowledge-repo#69]
First, on v0.6.5 deploying the web app does not work correctly.  Pages are not rendering with an error message displayed but moving back down to v0.6.3 the bug disappears.  When I run a preview of a Knowledge Post it renders correctly, the issue only occurs when I initiate a server, either via `deploy` or `runserver`.

Second, thanks for a great application.  Is raising an issue the best way to raise any bugs or other feedback?  I found the documentation very clear and easy to step through to get up and running very quickly.

**Comment by NiharikaRay** [comment]
Hi! Thanks for the feedback! Raising an issue is the best way to communicate feedback - I've just added the bug label here for clarity. 

Could you gives us the error message you're seeing? I tried to reproduce the issue on my side but was able to load the web app.

**Comment by NiharikaRay** [comment]
We just added a bugfix for this - could you retry this and let us know if you're still seeing an issue?

**Comment by Cleopatro** [comment]
It seems not work in v0.6.6. 

When I run `knowledge_repo --repo ./ runserver`, `localhost:7000` will redirect to `localhost:7000/feed`. It goes well on the `feed` page. However, when I click any of link on this page, a new page shows with the message "Uh oh! Looks like something broke
Try clicking around on the other links while we try and get this page up and running". 

Interesting, When I run `knowledge_repo --repo ./ preview public/demo`, chrome (my default browser) opens `http://127.0.0.1:7000/render?markdown=public/demo.kp`. It works. In this circumstance, I navigate to `feed` or home page, the repo list doesn't show.

Could you please tell me that my usage is incorrect, or just the `knowledge_repo` has not yet covered this usage?

**Comment by earthmancash** [comment]
Having a look. I'm guessing this might be a regression from the EXCLUDED_TAGS concept we introduced, will let you know when I figure it out.

**Comment by earthmancash** [comment]
@Cleopatro I think this fix took care of the issue https://github.com/airbnb/knowledge-repo/pull/81. Can you re-run and add the debug flag? so `knowledge_repo --repo ./ --debug runserver` and send us the output? 

If you see this error, then it's the one that the latest bug fixed, and pulling the changes should fix it.

```
line 316, in contains_excluded_tag
    if tag.name in excluded_tags:
TypeError: argument of type 'NoneType' is not iterable
```
