### ISSUE TITLE
Error when adding an md post on a python 3.5 environment

### ISSUE THREAD

**Issue by qthurier** [airbnb/knowledge-repo#75]
I'm using the 0.6.6 version + python 3.5. I got error adding md posts:

![screen shot 2016-10-13 at 10 12 37 am](https://cloud.githubusercontent.com/assets/4801331/19327979/3448d54c-912e-11e6-83eb-45abaaf5f874.png)

**Comment by earthmancash** [comment]
From the error messages, it looks like this is an issue on the byte64 encoding of local images on post contribution. We'll have a look and try to replicate the bug in python 3.5

**Comment by matthewwardrop** [comment]
This is fixed as of latest master; and will be part of v0.6.7 when that gets released.
