### ISSUE TITLE
Documentation: How to set users

### ISSUE THREAD

**Issue by kaelhuerta** [airbnb/knowledge-repo#91]
Hi, I'm still testing out the knowledge repo and I have a question.

I'm getting always the **knowledge_default** user.
How to set up users and emails?

Could you elaborate more on this on the documentation?

Thanks a lot!

Also, where to leave feedback? as an issue on Github?

**Comment by earthmancash** [comment]
That's a good point, we don't have much documentation on where each of the config files are. I'll take a pass at upgrading that documentation, in the mean time, here's the [sample config](https://github.com/airbnb/knowledge-repo/blob/master/resources/server_config.py#L48-L49) username parsing lines. When starting the app, you can use a server config file by adding a `--config /path/to/server_config.py` to your call.

**Comment by earthmancash** [comment]
To make it more clear how that config value is used, have a look here https://github.com/airbnb/knowledge-repo/blob/e5aaeef74f7f81544372b1f2f9c61bafe4f69b46/knowledge_repo/app/app.py#L127

**Comment by kaelhuerta** [comment]
Thanks a lot!

**Comment by earthmancash** [comment]
Added a bit of detail here https://github.com/airbnb/knowledge-repo/pull/92

**Comment by matthewwardrop** [comment]
I think the issue in this post has been addressed. Closing!

**Comment by shashj199** [comment]
@matthewwardrop This seems like it will track user which has deployed the knowledge repo. Is it also possible to track users which are viewing the deployed flask instance? Is it possible to include a login feature?

Thanks
