### ISSUE TITLE
Params do no get passed correctly to pagination

### ISSUE THREAD

**Issue by NiharikaRay** [airbnb/knowledge-repo#94]
If you click on an author in a knowledge post, you arrive at a feed for the author. Clicking the next arrow returns you to the second page of the feed, without the author being set. 

This is a bigger issue with how to deal with parameters (currently done hackily), I'll take this fix on.

**Comment by earthmancash** [comment]
Fixed here https://github.com/airbnb/knowledge-repo/pull/150
