### ISSUE TITLE
Documentation: extra files

### ISSUE THREAD

**Issue by Pl-Mrcy** [airbnb/knowledge-repo#95]
Hi, I'm still testing out the knowledge repo and I have a question:

I did not see anywhere what is the prefered way to add extra files (ex: excel files, sql files,...) in the commit when you submit your blog post.

Is there also any way to automatically have a list of all the extra files directly in the blog post?

Thank you !

**Comment by matthewwardrop** [comment]
Hi @Pl-Mrcy,

While our backends support adding these files, the front-end has yet to expose these "source" files for download (see issue #45).

To add the source files just add them in a space separated list after the keyword `--src` to the `add` action. For more details, refer to the help:

```
$ knowledge_repo add --help
usage: knowledge_repo add [-h] [-p PATH] [--update] [--branch BRANCH]
                          [--squash] [--submit] [-m MESSAGE]
                          [--src SRC [SRC ...]]
                          filename

positional arguments:
  filename              The filename to add.

optional arguments:
  -h, --help            show this help message and exit
  -p PATH, --path PATH  The path of the destination post to be added in the
                        knowledge repo. Required if the knowledge post does
                        not specify "path" in its headers.
  --update              Whether this should update an existing post of the
                        same name.
  --branch BRANCH       The branch to use for this addition, if not the
                        default (which is the path of the knowledge post).
  --squash              Automatically suppress all previous commits, and
                        replace it with this version.
  --submit              Submit newly added post
  -m MESSAGE, --message MESSAGE
                        The commit message to be used when committing into the
                        repo.
  --src SRC [SRC ...]   Specify additional source files to add to
                        <knowledge_post>/orig_src.
```

An example of adding an excel spreadsheet as an "attachment" or "adjunct" file to a knowledge post would be:
`knowledge_repo add post/test.kp -p projects/test --src test.xslx`

Let me know if you have any more questions.

**Comment by Pl-Mrcy** [comment]
Hi Matthew,

I indeed hadn't read the help well enough. You solved my problem.
However I didn't succeed in adding a folder (with multiple files inside) using this option.

```knowledge_repo add post/test.kp -p projects/test --src test_folder/```

This would add the entire test_folder to projects/test/orig_src.

Thank you very much for your quick answer and for this great work !

**Comment by matthewwardrop** [comment]
@Pl-Mrcy Yeah... I don't think I could decide at the time whether we wanted to support that (it runs the risk of repositories getting really bloated). Will have to think some more on this, I think...
